export const HINTS_WORD_BANK = {
"Countries": {
"Sweden": "Nordic",
"South Africa": "Safari",
"Norway": "Fjords",
"Denmark": "Kingdom",
"Finland": "Lakes",
"Iceland": "Volcanic",
"Germany": "Federal",
"France": "Republic",
"Spain": "Iberian",
"Italy": "Peninsula",
"Portugal": "Atlantic",
"United Kingdom": "Island",
"Ireland": "Emerald",
"Netherlands": "Canals",
"Switzerland": "Alpine",
"United States": "Federal",
"Canada": "Maple",
"Mexico": "Aztec",
"Brazil": "Amazon",
"Argentina": "Patagonia",
"Japan": "Archipelago",
"China": "Dynasty",
"South Korea": "Peninsula",
"India": "Monsoon",
"Thailand": "Tropical",
"Australia": "Outback",
"New Zealand": "Island",
"Russia": "Vast",
"Poland": "Central",
"Malta": "Mediterranean",
"Turkey": "Strait",
"Greece": "Aegean",
"Egypt": "Nile",
"Nigeria": "WestAfrican",
"Maldives": "Atolls",
"North Korea": "Isolated",
"Kenya": "Savanna",
"Tanzania": "Safari"
},
  "Celebrities": {
    "Tom Cruise": "Acting",
    "Greta Thunberg": "Activist",
    "Avicii": "Music",
"Felix Herngren": "Comedy",
"JLC": "YouTube",
"Loreen": "Eurovision",
"Avicii": "DJ",
"Zlatan Ibrahimovic": "Sports",
"Björn Borg": "Sports",
"Ingemar Stenmark": "Sports",
"Henrik Lundqvist": "Sports",
"Sarah Sjöström": "Sports",
"Armand Duplantis": "Sports",
"Max Martin": "Songwriter",
"Robyn": "Pop",
"Håkan Hellström": "Gothenburg",
"Veronica Maggio": "Pop",
"Carola Häggkvist": "Singer",
"Petter": "Rap",
"Måns Zelmerlöw": "Eurovision",
"Alicia Vikander": "Acting",
"Alexander Skarsgård": "Acting",
"Stellan Skarsgård": "Acting",
"Carl XVI Gustav": "Monarchy",
"Tove Lo": "Pop",
"Lykke Li": "Music",
"PewDiePie": "Gaming",
"Notch": "Gaming",
"Markoolio": "Comedy",
"Truls Möregårdh": "Sports",
"Stefan Löfven": "Politics",
"Jimmie Åkesson": "Politics",
"Magdalena Andersson": "Politics",
"Ulf Kristersson": "Politics",
"Fredrik Reinfeldt": "Politics",
"Benjamin Ingrosso": "Music",
"Cornelia Jakobs": "Eurovision",
"David Batra": "TV",
"Petra Mede": "TV",
"Zara Larsson": "Pop",
"HOV1": "Group",
"Bolaget": "Group",
"Messiah Hallberg": "Satire",
"Tony Irving": "Dance",
"David Hellenius": "TV",
"Pernilla Wahlgren": "Entertainment",
"Henrik Dorsin": "Comedy",
"Tusse": "Idol",
"Jonas Andersson (RMM)": "YouTube",
"Johan Rheborg": "Comedy",
"Robert Gustafsson": "Humor",
"Bianca Ingrosso": "Influencer",
"Ebba Busch": "Politics",
"Yung Lean": "Rap",
"Samir Badran": "Reality",
"Viktor Frisk": "Influencer",
"Paow": "Blogging",
"Peter Stormare": "Hollywood",
"Arga snickaren": "Renovation",
"John Lundvik": "Melodifestival",
"Eric Saade": "Pop",
"Lotta Schelin": "Football",
"Anis Don Demina": "YouTube",
"Dermot Clemenger": "Dance",
"Alexander Ernstberger": "Finance",
"Gunilla Persson": "TV",
"Fröken Snusk": "Music",
"Pontus Rasmusson": "YouTube",
"Edvin Törnblom": "Podcast",
"Johanna Nordström": "Comedy",
"Rickard Olsson": "Hosting",
"Isabella Löwengrip": "Entrepreneur",
"Paolo Roberto": "Scandal",
"Maria Montazami": "Reality",
"Leif GW Persson": "Crime",
"Jan Emanuel": "Politics",
    "Rihanna": "Singer",
"Ariana Grande": "Pop",
"Drake": "Toronto",
"Donald Trump": "Politics",
"Ed Sheeran": "Ginger",
"Billie Eilish": "Alternative",
"The Weekend": "Falsetto",
"Justin Bieber": "Pop",
"Beyoncé": "Icon",
"Dua Lipa": "Pop",
"Harry Styles": "Boyband",
"Eminem": "Rap",
"Kanye West": "Producer",
"Nicki Minaj": "Rap",
"Bad Bunny": "Latin",
"Elton John": "Piano",
"Madonna": "Pop",
"Michael Jackson": "Moonwalk",
"Frank Ocean": "R&B",
"Sam Smith": "Ballads",
"Lana Del Rey": "Dreamy",
"Bruno Mars": "Funk",
"Shakira": "Colombian",
"Katy Perry": "Pop",
"Olivia Rodrigo": "Breakout",
"Cristiano Ronaldo": "Football",
"Lionel Messi": "Football",
"Erling Haaland": "Striker",
"LeBron James": "Basketball",
"Serena Williams": "Tennis",
"Neymar": "Brazilian",
"Roger Federer": "Tennis",
"Max Verstappen": "Racing",
"Lewis Hamilton": "Formula1",
"Leonardo DiCaprio": "Oscars",
"Brad Pitt": "Hollywood",
"Tom Hanks": "Hollywood",
"Dwayne Johnson": "Wrestling",
"Johnny Depp": "Pirates",
"Charlie Kirk": "Commentary",
"Ryan Gosling": "Hollywood",
"Margot Robbie": "Australian",
"Zendaya": "Euphoria",
"Robert Downey Jr.": "Marvel",
"Chris Hemsworth": "Marvel",
"Chris Evans": "Marvel",
"Anne Hathaway": "Acting",
"Emma Stone": "Oscars",
"Jennifer Lawrence": "HungerGames",
"Will Smith": "Hollywood",
"Keanu Reeves": "Action",
"Jeffery Epstein": "Scandal",
"MrBeast": "YouTube",
"KSI": "YouTube",
"Logan Paul": "Boxing",
"IShowSpeed": "Streaming",
"Sidemen": "Group"
  },
"Movies & TV": {
"Breaking Bad": "Chemistry",
"Ove Sundberg": "Cringe",
"Game of Thrones": "Dragons",
"Friends": "Sitcom",
"The Office": "Workplace",
"Stranger Things": "D&D",
"Harry Potter": "Magic",
"Star Wars": "Galaxy",
"Arrested Development": "Family",
"The Lion King": "Savanna",
"Titanic": "Ship",
"Inception": "Dreams",
"The Dark Knight": "Gotham",
"Forrest Gump": "Bench",
"Shrek": "Ogre",
"Avatar": "Pandora",
"Frozen": "Snow",
"Toy Story": "Toys",
"The Simpsons": "Springfield",
"Interstellar": "Space",
"The Matrix": "Simulation",
"Jurassic Park": "Dinosaurs",
"Lord of the Rings": "Middleearth",
"The Hobbit": "Quest",
"The Hunger Games": "Arena",
"Pirates of the Caribbean": "Pirates",
"Gladiator": "Rome",
"Mission Impossible": "Spy",
"Fast & Furious": "Cars",
"Black Panther": "Wakanda",
"Guardians of the Galaxy": "Marvel",
"The Avengers": "Marvel",
"Deadpool": "Antihero",
"The Walking Dead": "Zombies",
"Peaky Blinders": "Gangsters",
"Narcos": "Cartel",
"Money Heist": "Heist",
"The Crown": "Royalty",
"Wednesday": "Gothic",
"Squid Game": "Survival",
"How I Met Your Mother": "Sitcom",
"Brooklyn Nine-Nine": "Police",
"Family Guy": "Animated",
"South Park": "Satire",
"Rick and Morty": "Multiverse",
"Minions": "Yellow",
"Cars": "Racing",
"Modern Family": "Sitcom",
"Störst av allt": "Courtroom",
"Solsidan": "Suburbia",
"Darth Vader": "Sith",
"Yoda": "Jedi",
"Spider-Man": "Marvel",
"Batman": "Gotham",
"Joker": "Chaos",
"Iron Man": "Armor",
"Walter White": "Meth",
"Homer Simpson": "Donuts",
"Fredrik Schiller": "Money"
},
"Professions": {
"Police Officer": "Uniform",
"Firefighter": "Rescue",
"Security Guard": "Patrol",
"Bouncer": "Door",
"Doctor": "Clinic",
"Nurse": "Care",
"Surgeon": "Operating",
"Dentist": "Teeth",
"Psychologist": "Therapy",
"Preschool Teacher": "Children",
"High School Teacher": "Classroom",
"Private Tutor": "Lessons",
"University Professor": "Academia",
"McDonalds Cashier": "Fastfood",
"Office Worker": "Desk",
"Programmer": "Code",
"Electrician": "Wiring",
"Plumber": "Pipes",
"Carpenter": "Woodwork",
"Construction Worker": "Building",
"Warehouse Worker": "Logistics",
"Delivery Driver": "Packages",
"Taxi Driver": "Transport",
"Truck Driver": "Freight",
"Store Clerk": "Retail",
"Cashier": "Checkout",
"Barista": "Coffee",
"Waiter": "Serving",
"Bartender": "Cocktails",
"Chef": "Kitchen",
"DJ": "Mixing",
"Musician": "Performance",
"Photographer": "Camera",
"Actor": "Stage",
"Journalist": "News",
"Airline Pilot": "Cockpit",
"Flight Attendant": "Cabin",
"Personal Trainer": "Fitness",
"Physiotherapist": "Rehab",
"Hair Stylist": "Salon",
"Makeup Artist": "Beauty",
"Real Estate Agent": "Housing",
"Car Salesperson": "Dealership",
"Streamer": "Live",
"YouTuber": "Videos",
"TikTok Creator": "Shortform",
"Influencer": "Social",
"Professional Gamer": "Esports",
"Entrepreneur": "Startup"
},
"Objects": {
"Phone": "Screen",
"Snus": "Pouch",
"Laptop": "Portable",
"AirPods": "Wireless",
"Charger": "Cable",
"Powerbank": "Battery",
"Wallet": "Pocket",
"Keys": "Metal",
"Backpack": "Carry",
"BankID": "Digital",
"Swish": "Payment",
"Coffee Mug": "Ceramic",
"Water Bottle": "Hydration",
"Sofa": "Livingroom",
"Bed": "Sleep",
"Mirror": "Reflection",
"Lamp": "Light",
"TV Remote": "Buttons",
"PlayStation Controller": "Gaming",
"Toothbrush": "Hygiene",
"Shampoo": "Shower",
"Perfume": "Scent",
"Umbrella": "Rain",
"Suitcase": "Travel",
"Football": "Sport",
"Tennis Racket": "Strings",
"Dice": "Rolling",
"Playing Cards": "Deck",
"Skis": "Winter",
"Snowboard": "Slope",
"Bicycle": "Pedals",
"Scooter": "Wheels",
"Credit Card": "Plastic",
"Passport": "Border",
"Driver’s License": "ID",
"Condom": "Protection",
"Lipstick": "Cosmetic",
"Makeup Bag": "Pouch",
"Protein Shake": "Gym",
"Energy Drink": "Caffeine",
"UNO Cards": "Colors",
"Monopoly": "Game",
"Beer Bottle": "Glass"
},
"Companies": {
"IKEA": "Furniture",
"Systembolaget": "Retail",
"Spotify": "Streaming",
"Volvo": "Automotive",
"ICA": "Groceries",
"Apoteket": "Pharmacy",
"Klarna": "Payments",
"Swish": "Payments",
"Max Burgers": "Fastfood",
"SAS": "Airline",
"PostNord": "Logistics",
"Northvolt": "Factory",
"Pepsi": "Soda",
"Coca-Cola": "Soda",
"Heineken": "Beer",
"Absolut Vodka": "Spirits",
"Red Bull": "Energy",
"Ben & Jerry’s": "Icecream",
"Apple": "Tech",
"Google": "Search",
"Microsoft": "Software",
"Amazon": "Ecommerce",
"Netflix": "Streaming",
"YouTube": "Video",
"TikTok": "Shortform",
"Instagram": "Social",
"Snapchat": "Messaging",
"Uber": "Rides",
"Airbnb": "Stays",
"Tesla": "Electric",
"H&M": "Fashion",
"Zara": "Fashion",
"Nike": "Sportswear",
"Adidas": "Sportswear",
"Shein": "Fastfashion",
"Zalando": "Fashion",
"New Balance": "Sneakers",
"McDonald's": "Fastfood",
"Burger King": "Fastfood",
"Starbucks": "Coffee"
}
};
