export const HINTS_PREDEFINED_CUSTOM = {
  "Famous cities": {
"Berlin": "Capital",
"Vancouver": "Harbor",
"Phuket": "Island",
"Brasília": "Capital",
"Canberra": "Inland",
"Copenhagen": "Nordic",
"Helsinki": "Baltic",
"London": "Royal",
"Madrid": "Iberian",
"Oslo": "Nordic",
"Ottawa": "Federal",
"Paris": "River",
"Rome": "Ancient",
"Stockholm": "Archipelago",
"Tokyo": "Megacity",
"Washington D.C.": "Federal",
"Beijing": "Capital",
"Reykjavik": "Geothermal",
"Dublin": "Literary",
"Warsaw": "Rebuilt",
"Prague": "Bohemian",
"Vienna": "Imperial",
"Budapest": "Danube",
"Athens": "Ancient",
"Lisbon": "Atlantic",
"Bern": "Alpine",
"Brussels": "Diplomatic",
"Ankara": "Plateau",
"Cairo": "Nile",
"Bangkok": "Canals",
"Seoul": "Tech",
"New Delhi": "Capital",
"Mexico City": "Plateau",
"Buenos Aires": "Port",
"Milano": "Fashion",
"Göteborg": "Port",
"Malmö": "Bridge",
"Uppsala": "University",
"Åre": "Ski",
"Barcelona": "Gaudi",
"Amsterdam": "Canals",
"Zurich": "Finance",
"Munich": "Bavarian",
"Hamburg": "Port",
"Frankfurt": "Finance",
"New York": "Skyline",
"Los Angeles": "Hollywood",
"Miami": "Beach",
"Las Vegas": "Casino",
"Chicago": "Lakeside",
"San Francisco": "Bay",
"Boston": "Academic",
"Toronto": "Skyline",
"Dubai": "Skyscrapers",
"Abu Dhabi": "Capital",
"Doha": "Gulf",
"Singapore": "Citystate",
"Hong Kong": "Harbor",
"Sydney": "Harbor",
"Rio de Janeiro": "Carnival",
"Cape Town": "Peninsula",
"Marrakech": "Market",
"Shanghai": "Skyline",
"Kyoto": "Temples",
"Osaka": "Food",
"Bali": "Temples",
"Maldives": "Atolls",
"Istanbul": "Strait",
"Ibiza": "Nightlife",
"Monaco": "Principality",
"Nice": "Riviera",
"Edinburgh": "Castle",
"Manchester": "Industrial",
"Val d'Isere": "Alpine",
"Zermatt": "Matterhorn",
"Chamonix": "Montblanc"
},
  "Famous landmarks": {
"Eiffel Tower": "Iron",
"Big Ben": "Clock",
"Colosseum": "Arena",
"Statue of Liberty": "Torch",
"Golden Gate Bridge": "Suspension",
"Mount Rushmore": "Carved",
"Great Wall of China": "Fortification",
"Taj Mahal": "Marble",
"Petra": "Rockcut",
"Angkor Wat": "Temple",
"Machu Picchu": "Incan",
"Christ the Redeemer": "Summit",
"Sydney Opera House": "Sails",
"Burj Khalifa": "Skyscraper",
"Stonehenge": "Megalithic",
"Turning Torso": "Twisted",
"Vasa Museum": "Warship",
"Gamla Stan": "Oldtown",
"Stockholm City Hall": "Banquet",
"Öresund Bridge": "Link",
"Icehotel Jukkasjärvi": "Frozen",
"Kalmar Castle": "Fortress",
"Uppsala Cathedral": "Spires",
"Brandenburg Gate": "Gateway",
"Empire State Building": "ArtDeco",
"Sagrada Família": "Basilica",
"Acropolis": "Citadel",
"Niagara Falls": "Waterfall"
},
"Swedish celebrities": {
"Felix Herngren": "Comedy",
"JLC": "YouTube",
"Loreen": "Eurovision",
"Avicii": "DJ",
"Zlatan Ibrahimovic": "Sports",
"Björn Borg": "Sports",
"Ingemar Stenmark": "Sports",
"Henrik Lundqvist": "Sports",
"Sarah Sjöström": "Sports",
"Armand Duplantis": "Sports",
"Max Martin": "Songwriter",
"Robyn": "Pop",
"Håkan Hellström": "Gothenburg",
"Veronica Maggio": "Pop",
"Carola Häggkvist": "Singer",
"Petter": "Rap",
"Måns Zelmerlöw": "Eurovision",
"Alicia Vikander": "Acting",
"Alexander Skarsgård": "Acting",
"Stellan Skarsgård": "Acting",
"Carl XVI Gustav": "Monarchy",
"Tove Lo": "Pop",
"Lykke Li": "Music",
"PewDiePie": "Gaming",
"Notch": "Gaming",
"Markoolio": "Comedy",
"Truls Möregårdh": "Sports",
"Stefan Löfven": "Politics",
"Jimmie Åkesson": "Politics",
"Magdalena Andersson": "Politics",
"Ulf Kristersson": "Politics",
"Fredrik Reinfeldt": "Politics",
"Benjamin Ingrosso": "Music",
"Cornelia Jakobs": "Eurovision",
"David Batra": "TV",
"Petra Mede": "TV",
"Zara Larsson": "Pop",
"HOV1": "Group",
"Bolaget": "Group",
"Messiah Hallberg": "Satire",
"Tony Irving": "Dance",
"David Hellenius": "TV",
"Pernilla Wahlgren": "Entertainment",
"Henrik Dorsin": "Comedy",
"Tusse": "Idol",
"Jonas Andersson (RMM)": "YouTube",
"Johan Rheborg": "Comedy",
"Robert Gustafsson": "Humor",
"Bianca Ingrosso": "Influencer",
"Ebba Busch": "Politics",
"Yung Lean": "Rap",
"Samir Badran": "Reality",
"Viktor Frisk": "Influencer",
"Paow": "Blogging",
"Peter Stormare": "Hollywood",
"Arga snickaren": "Renovation",
"John Lundvik": "Melodifestival",
"Eric Saade": "Pop",
"Lotta Schelin": "Football",
"Anis Don Demina": "YouTube",
"Dermot Clemenger": "Dance",
"Alexander Ernstberger": "Finance",
"Gunilla Persson": "TV",
"Fröken Snusk": "Music",
"Pontus Rasmusson": "YouTube",
"Edvin Törnblom": "Podcast",
"Johanna Nordström": "Comedy",
"Rickard Olsson": "Hosting",
"Isabella Löwengrip": "Entrepreneur",
"Paolo Roberto": "Scandal",
"Maria Montazami": "Reality",
"Leif GW Persson": "Crime",
"Jan Emanuel": "Politics"
},
"Swedish influencers": {
"Bianca Ingrosso": "Influencer",
"Therese Lindgren": "YouTube",
"Johanna Nordström": "Comedy",
"Joakim Lundell": "YouTube",
"Jonna Lundell": "YouTube",
"Matilda Djerf": "Fashion",
"Alice Stenlöf": "Lifestyle",
"Margaux Dietz": "Lifestyle",
"Clara Henry": "YouTube",
"Anis Don Demina": "YouTube",
"Keyyo": "Comedy",
"Jon Olsson": "Lifestyle",
"Lovisa Barkman": "Fashion",
"Lovisa Worge": "Lifestyle",
"Hanna Schönberg": "Fashion",
"Hanna Friberg": "Lifestyle",
"Wilma Holmqvist": "Beauty",
"Isa Östling": "Lifestyle",
"Antonija Mandir": "Lifestyle",
"IJustWantToBeCool": "Comedy",
"Edvin Törnblom": "Podcast",
"JLC": "YouTube",
"Random Making Movies": "YouTube",
"STHLM Panda": "Pranks",
"Filip Dikmen": "Comedy",
"Hampus Hedström": "Comedy",
"Tan by Klara": "Beauty",
"Emelie Lindmark": "Beauty",
"Sofie Karlstad": "Lifestyle",
"Amilia Stapelfeldt": "Lifestyle",
"Christofer Westerlund": "Lifestyle",
"Isabella Löwengrip": "Entrepreneur",
"Kenza Zouiten": "Fashion",
"Sofie Fahrman": "Fashion",
},
"Places in Sweden": {
    "Stockholm": "Capital",
    "Boden": "Garrison",
    "Lidingö": "Island",
    "Visby": "Medieval",
    "Nacka": "Suburb",
    "Bromma": "Airport",
    "Rinkeby": "Suburb",
    "Tensta": "Suburb",
    "Södertälje": "Canal",
    "Täby": "Suburb",
    "Sollentuna": "Commuter",
    "Upplands Väsby": "Commuter",
    "Huddinge": "Municipality",
    "Nynäshamn": "Harbor",
    "Västerås": "Lake",
    "Uppsala": "University",
    "Strängnäs": "Cathedral",
    "Enköping": "Parks",
    "Norrtälje": "Archipelago",
    "Örebro": "Castle",
    "Eskilstuna": "Industry",
    "Linköping": "University",
    "Nyköping": "Coastal",
    "Västervik": "Archipelago",
    "Kalmar": "Castle",
    "Karlskrona": "Naval",
    "Halmstad": "Seaside",
    "Helsingborg": "Ferry",
    "Lund": "University",
    "Malmö": "Bridge",
    "Ystad": "Wallander",
    "Trelleborg": "Port",
    "Göteborg": "Harbor",
    "Båstad": "Tennis",
    "Falsterbo": "Beach",
    "Örkeljunga": "Inland"
  },
  "Stranger Things": {
    "Eleven": "Psychic",
    "Mike Wheeler": "Leader",
    "Dustin Henderson": "Curious",
    "Lucas Sinclair": "Skeptic",
    "Will Byers": "Missing",
    "Max Mayfield": "Skater",
    "Hopper": "Sheriff",
    "Joyce Byers": "Mother",
    "Vecna": "Villain",
    "Mind Flayer": "Shadow",
    "Demogorgon": "Monster",
    "Demodog": "Creature",
    "Upside Down": "Dimension",
    "Hawkins": "Town",
    "Starcourt Mall": "Mall",
    "Eggo waffles": "Breakfast",
    "Hellfire Club": "DND",
    "Eddie Munson": "Metalhead",
    "Season 1": "Beginnings",
    "Christmas lights": "Signals",
    "Season 2": "Possession",
    "Season 3": "Mall",
    "Final Season": "Ending"
  }, "The Office": {
    "Michael Scott": "Manager",
    "Dwight Schrute": "Beets",
    "Jim Halpert": "Pranks",
    "Pam Beesly": "Reception",
    "Andy Bernard": "Cornell",
    "Stanley Hudson": "Pretzel",
    "Kevin Malone": "Chili",
    "Angela Martin": "Cats",
    "Oscar Martinez": "Accountant",
    "Creed Bratton": "Weird",
    "Toby Flenderson": "HR",
    "Todd Packer": "Sales",
    "Jan Levinson": "Corporate",
    "Dunder Mifflin": "Paper",
    "Scranton": "Branch",
    "World’s Best Boss": "Mug",
    "Pranks": "Jim",
    "Beets": "Dwight",
    "Fun run": "Rabies",
    "Phyllis Vance": "Sales",
    "Bob Vance": "Refrigeration",
    "Ryan the temp": "Temp",
    "Kelly Kapoor": "Gossip",
    "Prison Mike": "Alterego",
    "That’s what she said": "Catchphrase",
    "Office Olympics": "Games",
    "Pretzel Day": "Snack",
    "Conference Room": "Meetings",
    "Dinner Party": "Cringe",
    "The warehouse": "Downstairs"
  },
  "Friends": {
    "Rachel Green": "Fashion",
    "Ross Geller": "Dinosaurs",
    "Monica Geller": "Chef",
    "Chandler Bing": "Sarcasm",
    "Joey Tribbiani": "Actor",
    "Phoebe Buffay": "Eccentric",
    "Janice": "Laugh",
    "Central Perk": "Cafe",
    "Smelly Cat": "Song",
    "Pivot": "Couch",
    "We were on a break": "Catchphrase",
    "Apartment": "Purple",
    "Thanksgiving": "Tradition",
    "Coffee": "Cafe",
    "New York": "Setting",
    "Gunther": "Barista",
    "The Couch": "Pivot",
    "Wedding in London": "Finale",
    "Holiday Armadillo": "Costume"
  },
  "Breaking Bad": {
    "Walter White": "Chemistry",
    "Jesse Pinkman": "Partner",
    "Saul Goodman": "Lawyer",
    "Skyler White": "Family",
    "Hank Schrader": "DEA",
    "Gus Fring": "Chicken",
    "Mike Ehrmantraut": "Fixer",
    "Heisenberg": "Alias",
    "Los Pollos Hermanos": "Restaurant",
    "Blue meth": "Product",
    "RV": "Lab",
    "DEA": "Agency",
    "Chemistry": "Science",
    "Albuquerque": "Desert",
    "Say my name": "Quote",
    "Better Call Saul": "Spinoff",
    "Money barrel": "Desert",
    "Car wash": "Front"
  },
  "Game of Thrones": {
    "Jon Snow": "North",
    "Daenerys Targaryen": "Dragons",
    "Tyrion Lannister": "Wit",
    "Arya Stark": "Faceless",
    "Sansa Stark": "Winterfell",
    "Cersei Lannister": "Queen",
    "Jaime Lannister": "Kingslayer",
    "Night King": "Undead",
    "White Walkers": "Winter",
    "Dragons": "Fire",
    "Winterfell": "North",
    "King’s Landing": "Capital",
    "Iron Throne": "Seat",
    "House Stark": "Wolf",
    "House Lannister": "Lion",
    "The Wall": "Ice",
    "Red Wedding": "Massacre",
    "Mother of Dragons": "Title"
  },
  "Disney": {
    "Mickey Mouse": "Mascot",
    "Donald Duck": "Sailor",
    "Goofy": "Clumsy",
    "Elsa": "Ice",
    "Anna": "Sister",
    "Simba": "Lion",
    "Ariel": "Mermaid",
    "Belle": "Books",
    "Aladdin": "Lamp",
    "Genie": "Wish",
    "Buzz Lightyear": "Space",
    "Woody": "Cowboy",
    "Cinderella": "Slipper",
    "Snow White": "Apple",
    "Stitch": "Alien",
    "Moana": "Ocean",
    "Mulan": "Warrior",
    "Rapunzel": "Tower",
    "Olaf": "Snowman",
    "Peter Pan": "Neverland",
    "Tinker Bell": "Fairy"
  },
  "Harry Potter": {
    "Harry Potter": "Wizard",
    "Hermione Granger": "Brilliant",
    "Ron Weasley": "Loyal",
    "Albus Dumbledore": "Headmaster",
    "Severus Snape": "Potions",
    "Voldemort": "Darklord",
    "Draco Malfoy": "Slytherin",
    "Hagrid": "Groundskeeper",
    "Sirius Black": "Godfather",
    "Hogwarts": "Castle",
    "Dudley": "Muggle",
    "Cedric Diggory": "Champion",
    "Cho Chang": "Seeker",
    "Gryffindor": "House",
    "Slytherin": "House",
    "Hufflepuff": "House",
    "Ravenclaw": "House",
    "Quidditch": "Brooms",
    "Remus Lupin": "Werewolf",
    "Hedwig": "Owl",
    "Dobby": "Elf",
    "Azkaban": "Prison",
    "The Sorting Hat": "Hat",
    "Expelliarmus": "Spell",
    "The half blood prine": "Prince",
    "Triwizard tournament": "Tournament"
  },
  "Marvel Cinematic Universe": {
    "Iron Man": "Armor",
    "Captain America": "Shield",
    "Thor": "Hammer",
    "Hulk": "Smash",
    "Black Widow": "Spy",
    "Hawkeye": "Archer",
    "Spider-Man": "Webs",
    "Doctor Strange": "Magic",
    "Black Panther": "Wakanda",
    "Scarlet Witch": "Chaos",
    "Loki": "Trickster",
    "Ant-Man": "Shrinking",
    "Guardians of the Galaxy": "Cosmic",
    "Avengers": "Team",
    "Thanos": "Titan",
    "Infinity Stones": "Gems",
    "Wakanda": "Kingdom",
    "Nick Fury": "Eyepatch",
    "Deadpool": "Mercenary"
  },
  "Animals": {
    "Dog": "Pet",
    "Cat": "Whiskers",
    "Horse": "Hooves",
    "Rabbit": "Ears",
    "Bear": "Forest",
    "Wolf": "Pack",
    "Lion": "Savanna",
    "Tiger": "Stripes",
    "Elephant": "Trunk",
    "Giraffe": "Neck",
    "Zebra": "Stripes",
    "Panda": "Bamboo",
    "Kangaroo": "Pouch",
    "Dolphin": "Ocean",
    "Eagle": "Wings",
    "Shark": "Fins",
    "Whale": "Giant",
    "Penguin": "Antarctic",
    "Fox": "Cunning",
    "Owl": "Nocturnal",
    "Monkey": "Primate",
    "Moose": "Antlers"
  },
  "School subjects": {
    "Mathematics": "Numbers",
    "English": "Language",
    "History": "Past",
    "Geography": "Maps",
    "Biology": "Life",
    "Chemistry": "Molecules",
    "Physics": "Forces",
    "Computer Science": "Coding",
    "Economics": "Markets",
    "Civics": "Society",
    "Psychology": "Mind",
    "Philosophy": "Thinking",
    "Art": "Creative",
    "Music": "Melody",
    "Physical Education": "Sports",
    "Drama": "Theatre",
    "Religion": "Beliefs",
    "French": "Language",
    "Spanish": "Language"
  },
  "Sports": {
    "Football": "Goals",
    "Basketball": "Hoops",
    "Tennis": "Racket",
    "Hockey": "Sticks",
    "Ice hockey": "Puck",
    "Baseball": "Bat",
    "Cricket": "Wicket",
    "Rugby": "Tackles",
    "Golf": "Clubs",
    "Athletics": "Track",
    "Running": "Pace",
    "Swimming": "Pool",
    "Volleyball": "Net",
    "Badminton": "Shuttle",
    "Boxing": "Gloves",
    "Martial arts": "Discipline",
    "Cycling": "Pedals",
    "Skiing": "Slopes",
    "Snowboarding": "Board",
    "Ice skating": "Rink",
    "Figure skating": "Routine",
    "Roller skating": "Wheels",
    "Motorsport": "Racing",
    "Disc golf": "Frisbee",
    "Bowling": "Pins",
    "Handball": "Indoor",
    "Padel": "Glass",
    "Ping pong": "Table",
    "Pool": "Cue",
    "Darts": "Bullseye",
    "Surfing": "Waves",
    "Wind surfing": "Sail",
    "Water skiing": "Towrope",
    "Jet skiing": "Watercraft",
    "Karate": "Kata",
    "Taekwondo": "Kicks",
    "Judo": "Throws",
    "Kickboxing": "Strikes",
    "Sumo wrestling": "Ring",
    "Fencing": "Foil",
    "Gymnastics": "Balance",
    "Weight lifting": "Barbell",
    "Archery": "Bow",
    "Fishing": "Rod",
    "Horse racing": "Track",
    "Rock climbing": "Grip",
    "Scuba diving": "Oxygen",
    "Skateboarding": "Deck",
    "Street hockey": "Asphalt",
    "Sky diving": "Parachute",
    "Hang gliding": "Glider",
    "Bungee jumping": "Cord",
    "Chess": "Strategy",
    "E-sports": "Competitive"
  },
  "Athletes": {
    "Lionel Messi": "Football",
    "Sarah Sjöström": "Swimming",
    "Shaquille O'Neal": "Basketball",
    "Cristiano Ronaldo": "Football",
    "Neymar": "Brazilian",
    "Diego Maradona": "Argentina",
    "Pelé": "Legend",
    "Ronaldinho": "Skill",
    "David Beckham": "FreeKick",
    "LeBron James": "Basketball",
    "Michael Jordan": "Bulls",
    "Kobe Bryant": "Lakers",
    "Kevin Durant": "Scoring",
    "Tom Brady": "Quarterback",
    "Babe Ruth": "Baseball",
    "Roger Federer": "Tennis",
    "Serena Williams": "Tennis",
    "Naomi Osaka": "Tennis",
    "Tiger Woods": "Golf",
    "Muhammad Ali": "Boxing",
    "Mike Tyson": "Boxing",
    "Floyd Mayweather": "Boxing",
    "Anthony Joshua": "Heavyweight",
    "Conor McGregor": "UFC",
    "Khabib Nurmagomedov": "UFC",
    "Jon Jones": "UFC",
    "Georges St-Pierre": "UFC",
    "Ronda Rousey": "MMA",
    "Amanda Nunes": "MMA",
    "Usain Bolt": "Sprint",
    "Michael Phelps": "Olympics",
    "Lewis Hamilton": "Formula1",
    "Max Verstappen": "Formula1",
    "Michael Schumacher": "Ferrari",
    "Arnold Schwarzenegger": "Bodybuilding",
    "The Rock": "Wrestling",
    "Zlatan Ibrahimović": "Football",
    "Björn Borg": "Tennis",
    "Armand Duplantis": "Polevault",
    "Henrik Lundqvist": "Hockey",
    "Ingemar Stenmark": "Skiing",
    "Truls Möregårdh": "Tabletennis"
  },
  "Allsvenskan teams": {
    "AIK": "Stockholm",
    "Djurgårdens IF": "Stockholm",
    "Hammarby IF": "Stockholm",
    "IFK Göteborg": "Gothenburg",
    "Malmö FF": "Skåne",
    "IF Elfsborg": "Borås",
    "BK Häcken": "Hisingen",
    "IFK Norrköping": "Norrköping",
    "Kalmar FF": "Småland",
    "IK Sirius": "Uppsala",
    "Halmstads BK": "Halmstad",
    "Degerfors IF": "Värmland",
    "Mjällby AIF": "Blekinge",
    "Varbergs BoIS": "Halland",
    "IF Brommapojkarna": "Bromma",
    "Örebro SK": "Örebro"
  },
  "Premier League teams": {
    "Manchester United": "Red",
    "Manchester City": "Blue",
    "Liverpool": "Anfield",
    "Arsenal": "London",
    "Chelsea": "London",
    "Tottenham Hotspur": "London",
    "Newcastle United": "NorthEast",
    "Aston Villa": "Birmingham",
    "West Ham United": "London",
    "Everton": "Merseyside",
    "Brighton": "Seaside",
    "Wolverhampton": "Wolves",
    "Crystal Palace": "London",
    "Brentford": "London",
    "Nottingham Forest": "Forest",
    "Leicester City": "Foxes"
  },
  "Tennis players": {
    "Roger Federer": "Swiss",
    "Rafael Nadal": "Clay",
    "Novak Djokovic": "Serbian",
    "Andy Murray": "British",
    "Carlos Alcaraz": "Spanish",
    "Daniil Medvedev": "Russian",
    "Jannik Sinner": "Italian",
    "Alexander Zverev": "German",
    "Stefanos Tsitsipas": "Greek",
    "Casper Ruud": "Norwegian",
    "Serena Williams": "Champion",
    "Venus Williams": "Champion",
    "Iga Świątek": "Polish",
    "Naomi Osaka": "Japanese",
    "Maria Sharapova": "Russian",
    "Björn Borg": "Swedish"
  },
  "Beer brands": {
    "Heineken": "Dutch",
    "Corona": "Mexican",
    "Mariestads": "Swedish",
    "Budweiser": "American",
    "Guinness": "Stout",
    "Carlsberg": "Danish",
    "Stella Artois": "Belgian",
    "Peroni": "Italian",
    "Asahi": "Japanese",
    "Modelo": "Mexican",
    "Kronenbourg": "French",
    "Beck’s": "German",
    "Coors": "American",
    "Miller": "American",
    "Samuel Adams": "Boston",
    "Pripps Blå": "Swedish",
    "Norrlands Guld": "Swedish",
    "Falcon": "Swedish",
    "Spendrups": "Brewery",
    "Åbro": "Brewery",
    "Sofiero": "Swedish",
    "Eriksberg": "Lager",
    "Lapin Kulta": "Finnish"
  },
  "Car brands": {
    "Toyota": "Japanese",
    "Volkswagen": "German",
    "Porsche": "Sports",
    "BMW": "German",
    "Mercedes-Benz": "Luxury",
    "Audi": "Quattro",
    "Volvo": "Swedish",
    "Ford": "American",
    "Chevrolet": "American",
    "Honda": "Japanese",
    "Hyundai": "Korean",
    "Kia": "Korean",
    "Nissan": "Japanese",
    "Mazda": "Japanese",
    "Tesla": "Electric",
    "Ferrari": "Italian",
    "Lamborghini": "Supercar",
    "Koenigsegg": "Hypercar"
  },
  "Clothing brands": {
    "Nike": "Sportswear",
    "Armani": "Italian",
    "New Balance": "Sneakers",
    "Adidas": "Sportswear",
    "Puma": "Sportswear",
    "H&M": "Swedish",
    "Zara": "Spanish",
    "Uniqlo": "Japanese",
    "Levi’s": "Denim",
    "Ralph Lauren": "Polo",
    "Tommy Hilfiger": "Preppy",
    "Calvin Klein": "Minimal",
    "Patagonia": "Outdoor",
    "Supreme": "Streetwear",
    "Gucci": "Luxury",
    "Prada": "Luxury",
    "Balenciaga": "Designer"
  },
  "Melodifestivalen": {
    "Carola": "Winner",
    "Loreen": "Eurovision",
    "Måns Zelmerlöw": "Eurovision",
    "Charlotte Perrelli": "Winner",
    "The Ark": "Glam",
    "Robin Bengtsson": "Contestant",
    "Benjamin Ingrosso": "Finalist",
    "Anna Bergendahl": "Melodifestival",
    "Eric Saade": "Popular",
    "Sanna Nielsen": "Winner",
    "John Lundvik": "Finalist",
    "Cornelia Jakobs": "Eurovision",
    "Tusse": "Winner",
    "Arvingarna": "Dansband",
    "Anders Bagge": "Jury",
    "Danny Saucedo": "Performer",
    "Alcazar": "Pop",
    "The Mamas": "Harmony",
    "Jill Johnson": "Country",
    "Lisa Ajax": "Idol",
    "Nano": "Soul",
    "Anna Book": "Classic",
    "Jessica Andersson": "Dansband",
    "Jon Henrik Fjällgren": "Joik"
  },
  "Popular artists": {
    "Taylor Swift": "Songwriter",
    "Ed Sheeran": "Guitar",
    "Beyoncé": "Icon",
    "Drake": "Toronto",
    "Ariana Grande": "Vocalist",
    "Billie Eilish": "Alternative",
    "The Weeknd": "Falsetto",
    "Justin Bieber": "Pop",
    "Rihanna": "Barbadian",
    "Adele": "Ballads",
    "Bruno Mars": "Funk",
    "Dua Lipa": "Dancepop",
    "Post Malone": "Melodic",
    "Lady Gaga": "Pop",
    "Harry Styles": "Boyband",
    "Olivia Rodrigo": "Breakout",
    "Shakira": "Colombian",
    "Katy Perry": "Pop",
    "SZA": "R&B",
    "Travis Scott": "Rap",
    "Doja Cat": "Versatile",
    "Nicki Minaj": "Rap",
    "Shawn Mendes": "Pop",
    "Miley Cyrus": "Pop",
    "Elton John": "Piano",
    "Michael Jackson": "Moonwalk",
    "Madonna": "Pop",
    "Bad Bunny": "Latin"
  },
  "Popular bands": {
    "Coldplay": "Stadium",
    "Imagine Dragons": "Anthems",
    "Maroon 5": "Poprock",
    "OneRepublic": "Poprock",
    "Red Hot Chili Peppers": "Funkrock",
    "ABBA": "Swedish",
    "Queen": "Classic",
    "Linkin Park": "NuMetal",
    "Green Day": "Punk",
    "U2": "Irish",
    "The Rolling Stones": "Legends",
    "Metallica": "Metal",
    "Arctic Monkeys": "British",
    "Foo Fighters": "Rock",
    "Nirvana": "Grunge",
    "The Beatles": "Liverpool",
    "Oasis": "Britpop",
    "Blink-182": "Poppunk",
    "The Killers": "LasVegas",
    "Kings of Leon": "Southern",
    "Bon Jovi": "Arena",
    "Guns N’ Roses": "Hardrock",
    "The Police": "Trio"
  },
  "Pre 2000’s Hits": {
    "Dancing Queen (ABBA)": "Disco",
    "Bohemian Rhapsody (Queen)": "Opera",
    "Billie Jean (Michael Jackson)": "Bassline",
    "Like a Prayer (Madonna)": "Pop",
    "Smells Like Teen Spirit (Nirvana)": "Grunge",
    "Livin’ on a Prayer (Bon Jovi)": "Arena",
    "Take On Me (a-ha)": "Synthpop",
    "Sweet Child O’ Mine (Guns N’ Roses)": "Riff",
    "I Will Survive (Gloria Gaynor)": "Disco",
    "Every Breath You Take (The Police)": "Sting",
    "Thriller (Michael Jackson)": "Halloween",
    "Hotel California (Eagles)": "Guitar",
    "Don’t Stop Believin’ (Journey)": "Anthem",
    "Girls Just Want to Have Fun (Cyndi Lauper)": "80s",
    "Beat It (Michael Jackson)": "Rockpop",
    "Eye of the Tiger (Survivor)": "Workout",
    "Summer of ’69 (Bryan Adams)": "Nostalgia",
    "Another Brick in the Wall (Pink Floyd)": "Chorus",
    "Sweet Dreams (Are Made of This) (Eurythmics)": "Synth",
    "With or Without You (U2)": "Anthem",
    "Careless Whisper (George Michael)": "Saxophone"
  },
  "2000’s Hits": {
    "Poker Face (Lady Gaga)": "Dancepop",
    "Umbrella (Rihanna)": "Rain",
    "Crazy in Love (Beyoncé)": "Brass",
    "Hey Ya! (Outkast)": "Funk",
    "Mr. Brightside (The Killers)": "Indierock",
    "Hips Don’t Lie (Shakira)": "Latin",
    "Yeah! (Usher)": "Club",
    "Since U Been Gone (Kelly Clarkson)": "Breakup",
    "Rolling in the Deep (Adele)": "Powerhouse",
    "Single Ladies (Beyoncé)": "Dance",
    "Viva La Vida (Coldplay)": "Strings",
    "Apologize (OneRepublic)": "Ballad",
    "Firework (Katy Perry)": "Anthem",
    "Tik Tok (Kesha)": "Party",
    "Clocks (Coldplay)": "Piano",
    "Toxic (Britney Spears)": "Pop",
    "In the End (Linkin Park)": "NuMetal",
    "Seven Nation Army (The White Stripes)": "Riff",
    "Complicated (Avril Lavigne)": "Poprock",
    "Low (Flo Rida)": "Club",
    "Empire State of Mind (Jay-Z)": "NewYork",
    "Disturbia (Rihanna)": "Darkpop",
    "Grenade (Bruno Mars)": "Ballad",
    "SexyBack (Justin Timberlake)": "Electropop",
    "Lose Yourself (Eminem)": "Rap"
  },
  "Recent hits": {
    "Blinding Lights (The Weeknd)": "Synthwave",
    "Shape of You (Ed Sheeran)": "Dancehall",
    "Dance Monkey (Tones and I)": "Viral",
    "As It Was (Harry Styles)": "Synthpop",
    "Levitating (Dua Lipa)": "Disco",
    "Someone You Loved (Lewis Capaldi)": "Ballad",
    "Bad Guy (Billie Eilish)": "Minimal",
    "Shallow (Lady Gaga)": "Duet",
    "Old Town Road (Lil Nas X)": "Crossover",
    "Despacito (Luis Fonsi)": "Latin",
    "Sunflower (Post Malone)": "Soundtrack",
    "Drivers License (Olivia Rodrigo)": "Breakup",
    "Stay (The Kid LAROI)": "Duet",
    "Watermelon Sugar (Harry Styles)": "Summer",
    "Rockstar (Post Malone)": "Rap",
    "Anti-Hero (Taylor Swift)": "Confessional",
    "Flowers (Miley Cyrus)": "Empowerment",
    "Industry Baby (Lil Nas X)": "Brass",
    "Montero (Lil Nas X)": "Controversial",
    "Heat Waves (Glass Animals)": "Indie",
    "Unholy (Sam Smith)": "Darkpop"
  },
  "Video games": {
    "Mario": "Plumber",
    "Luigi": "Green",
    "Princess Peach": "Castle",
    "Bowser": "Koopa",
    "Yoshi": "Dinosaur",
    "Donkey Kong": "Barrels",
    "Link": "Hyrule",
    "Zelda": "Princess",
    "Pikachu": "Electric",
    "Kirby": "Pink",
    "Samus": "Bountyhunter",
    "Wario": "Greedy",
    "Super Mario Bros": "Platformer",
    "The Legend of Zelda": "Adventure",
    "Pokémon": "Creatures",
    "Tetris": "Blocks",
    "Pac-Man": "Arcade",
    "Sonic the Hedgehog": "Speed",
    "Street Fighter": "Fighting",
    "Mortal Kombat": "Fatality",
    "Minecraft": "Blocks",
    "The Sims": "Life",
    "Grand Theft Auto": "Crime",
    "Call of Duty": "Shooter",
    "Halo": "SciFi",
    "FIFA": "Sport",
    "Fortnite": "Battle Royale",
    "Counter-Strike": "Tactical",
    "League of Legends": "MOBA",
    "World of Warcraft": "MMO",
    "Overwatch": "HeroShooter",
    "Valorant": "Tactical",
    "Red Dead Redemption": "Western",
    "The Last of Us": "Survival",
    "God of War": "Mythology",
    "Assassin’s Creed": "Stealth",
    "Skyrim": "Dragons",
    "Elden Ring": "Soulslike",
    "Cyberpunk 2077": "Futuristic",
    "Among Us": "Impostor",
    "Roblox": "Sandbox",
    "Clash of Clans": "Mobile",
    "Brawl Stars": "Mobile",
    "Animal Crossing": "Cozy",
    "Super Smash Bros": "Crossover",
    "Kratos": "Spartan",
    "Lara Croft": "Explorer",
    "Steve (Minecraft)": "Blocks",
    "Creeper": "Explosive",
    "Solid Snake": "Stealth"
  },
  "Alcoholic Beverages": {
    "Beer": "Hops",
    "Wine": "Grapes",
    "Red wine": "Tannins",
    "White wine": "Crisp",
    "Rosé": "Pink",
    "Whiskey": "Oak",
    "Vodka": "Clear",
    "Rum": "Sugarcane",
    "Gin": "Juniper",
    "Tequila": "Agave",
    "Cider": "Apples",
    "Champagne": "Sparkling",
    "Cognac": "French",
    "Brandy": "Distilled",
    "Liqueur": "Sweet",
    "Absinthe": "Herbal",
    "Sake": "Rice",
    "Mead": "Honey",
    "Akvavit": "Nordic",
    "Snaps": "Shot",
    "Brännvin": "Swedish",
    "Glögg": "Mulled",
    "Aperol": "Orange"
  },
  "Food & snacks": {
    "Pizza": "Slices",
    "Hamburger": "Bun",
    "Cheeseburger": "Cheese",
    "Hot Dog": "Sausage",
    "Kebab": "Grill",
    "Tacos": "Mexican",
    "Burrito": "Wrap",
    "Nachos": "Chips",
    "Fries": "Crispy",
    "Chicken Nuggets": "Fastfood",
    "Meatballs": "Swedish",
    "Kanelbulle": "Cinnamon",
    "Semla": "Cream",
    "Smörgåstårta": "Layered",
    "Prinsesstårta": "Marzipan",
    "Gravlax": "Cured",
    "Raggmunk": "Potato",
    "Surströmming": "Fermented",
    "Knäckebröd": "Crispbread",
    "Lussekatt": "Saffron",
    "Sushi": "Rice",
    "Pasta": "Italian",
    "Spaghetti Bolognese": "Sauce",
    "Lasagna": "Layers",
    "Ramen": "Noodles",
    "Pad Thai": "Thai",
    "Butter Chicken": "Curry",
    "Falafel": "Chickpeas",
    "Paella": "Spanish",
    "Dumplings": "Filled",
    "Chips": "Crunchy",
    "Popcorn": "Cinema",
    "Candy": "Sweet",
    "Chocolate": "Cocoa",
    "Marabou": "Swedish",
    "Salted Peanuts": "Snack",
    "Protein Bar": "Gym",
    "Energy Drink": "Caffeine",
    "Ice Cream": "Frozen",
    "Ben & Jerry’s": "Icecream",
    "Brownie": "Chocolate",
    "Cheesecake": "Creamy",
    "Cupcake": "Frosting",
    "Pancakes": "Breakfast",
    "Waffles": "Syrup",
    "Donut": "Glazed",
    "Macaron": "French",
    "Tiramisu": "Coffee",
    "Apple Pie": "Dessert",
    "Chokladboll": "NoBake",
    "Avocado": "Green",
    "Banana": "Peel",
    "Strawberries": "Summer",
    "Watermelon": "Juicy",
    "Salmon": "Fish",
    "Steak": "Grill",
    "Egg": "Breakfast",
    "Toast": "Bread",
    "Sandwich": "Lunch",
    "Yoghurt": "Dairy",
    "Coffee": "Caffeine",
    "Cappuccino": "Foam",
    "Latte": "Milk",
    "Milkshake": "Thick",
    "Smoothie": "Blended",
    "Cola": "Soda",
    "Fanta": "Orange",
    "Red Bull": "Energy",
    "Beer": "Lager",
    "Wine": "Bottle"
  }
};
