export const HINTS_WORD_BANK = {
  "Countries": {
    "Sweden": "Geography",
    "South Africa": "Geography",
    "Norway": "Geography",
    "Denmark": "Geography",
    "Finland": "Geography",
    "Iceland": "Geography",
    "Germany": "Geography",
    "France": "Geography",
    "Spain": "Geography",
    "Italy": "Geography",
    "Portugal": "Geography",
    "United Kingdom": "Geography",
    "Ireland": "Geography",
    "Netherlands": "Geography",
    "Switzerland": "Geography",
    "United States": "Geography",
    "Canada": "Geography",
    "Mexico": "Geography",
    "Brazil": "Geography",
    "Argentina": "Geography",
    "Japan": "Geography",
    "China": "Geography",
    "South Korea": "Geography",
    "India": "Geography",
    "Thailand": "Geography",
    "Australia": "Geography",
    "New Zealand": "Geography",
    "Russia": "Geography",
    "Poland": "Geography",
    "Malta": "Geography",
    "Turkey": "Geography",
    "Greece": "Geography",
    "Egypt": "Geography",
    "Nigeria": "Geography",
    "Maldives": "Geography",
    "North Korea": "Geography",
    "Kenya": "Geography",
    "Tanzania": "Geography"
  },
  "Celebrities": {
    "Tom Cruise": "Public figure",
    "Greta Thunberg": "Public figure",
    "Avicii": "Public figure",
    "Zlatan Ibrahimovic": "Public figure",
    "Taylor Swift": "Public figure",
    "Björn Borg": "Public figure",
    "Ingemar Stenmark": "Public figure",
    "Henrik Lundqvist": "Public figure",
    "Sarah Sjöström": "Public figure",
    "Armand Duplantis": "Public figure",
    "Max Martin": "Public figure",
    "Robyn": "Public figure",
    "Håkan Hellström": "Public figure",
    "Veronica Maggio": "Public figure",
    "Carola Häggkvist": "Public figure",
    "Petter": "Public figure",
    "Måns Zelmerlöw": "Public figure",
    "Alicia Vikander": "Public figure",
    "Alexander Skarsgård": "Public figure",
    "Stellan Skarsgård": "Public figure",
    "Tove Lo": "Public figure",
    "Lykke Li": "Public figure",
    "PewDiePie": "Public figure",
    "Notch": "Public figure",
    "Markoolio": "Public figure",
    "Truls Möregårdh": "Public figure",
    "Stefan Löfven": "Public figure",
    "Jimmie Åkesson": "Public figure",
    "Magdalena Andersson": "Public figure",
    "Ulf Kristersson": "Public figure",
    "Fredrik Reinfeldt": "Public figure",
    "Benjamin Ingrosso": "Public figure",
    "Loreen": "Public figure",
    "Cornelia Jakobs": "Public figure",
    "David Batra": "Public figure",
    "Petra Mede": "Public figure",
    "JLC": "Public figure",
    "Zara Larsson": "Public figure",
    "HOV1": "Public figure",
    "Bolaget": "Public figure",
    "Messiah Hallberg": "Public figure",
    "Tony Irving": "Public figure",
    "David Hellenius": "Public figure",
    "Pernilla Wahlgren": "Public figure",
    "Henrik Dorsin": "Public figure",
    "Felix Herngren": "Public figure",
    "Tusse": "Public figure",
    "Jonas Andersson (RMM)": "Public figure",
    "Johan Rheborg": "Public figure",
    "Robert Gustafsson": "Public figure",
    "Ebba Busch": "Public figure",
    "Yung Lean": "Public figure",
    "Samir Badran": "Public figure",
    "Viktor Frisk": "Public figure",
    "Paow": "Public figure",
    "Peter Stormare": "Public figure",
    "Arga snickaren": "Public figure",
    "John Lundvik": "Public figure",
    "Eric Saade": "Public figure",
    "Lotta Schelin": "Public figure",
    "Anis Don Demina": "Public figure",
    "Dermot Clemenger": "Public figure",
    "Alexander Ernstberger": "Public figure",
    "Gunilla Persson": "Public figure",
    "Fröken Snusk": "Public figure",
    "Pontus Rasmusson": "Public figure",
    "Edvin Törnblom": "Public figure",
    "Johanna Nordström": "Public figure",
    "Rickard Olsson": "Public figure",
    "Isabella Löwengrip": "Public figure",
    "Paolo Roberto": "Public figure",
    "Maria Montazami": "Public figure",
    "Leif GW Persson": "Public figure",
    "Jan Emanuel": "Public figure",
    "Rihanna": "Public figure",
    "Ariana Grande": "Public figure",
    "Drake": "Public figure",
    "Donald Trump": "Public figure",
    "Ed Sheeran": "Public figure",
    "Billie Eilish": "Public figure",
    "The Weeknd": "Public figure",
    "Justin Bieber": "Public figure",
    "Beyoncé": "Public figure",
    "Dua Lipa": "Public figure",
    "Harry Styles": "Public figure",
    "Eminem": "Public figure",
    "Kanye West": "Public figure",
    "Nicki Minaj": "Public figure",
    "Bad Bunny": "Public figure",
    "Elton John": "Public figure",
    "Madonna": "Public figure",
    "Michael Jackson": "Public figure",
    "Frank Ocean": "Public figure",
    "Sam Smith": "Public figure",
    "Lana Del Rey": "Public figure",
    "Bruno Mars": "Public figure",
    "Shakira": "Public figure",
    "Katy Perry": "Public figure",
    "Olivia Rodrigo": "Public figure",
    "Cristiano Ronaldo": "Public figure",
    "Lionel Messi": "Public figure",
    "Erling Haaland": "Public figure",
    "LeBron James": "Public figure",
    "Serena Williams": "Public figure",
    "Neymar": "Public figure",
    "Roger Federer": "Public figure",
    "Max Verstappen": "Public figure",
    "Lewis Hamilton": "Public figure",
    "Leonardo DiCaprio": "Public figure",
    "Brad Pitt": "Public figure",
    "Tom Hanks": "Public figure",
    "Dwayne Johnson": "Public figure",
    "Johnny Depp": "Public figure",
    "Charlie Kirk": "Public figure",
    "Ryan Gosling": "Public figure",
    "Margot Robbie": "Public figure",
    "Zendaya": "Public figure",
    "Robert Downey Jr.": "Public figure",
    "Chris Hemsworth": "Public figure",
    "Chris Evans": "Public figure",
    "Anne Hathaway": "Public figure",
    "Emma Stone": "Public figure",
    "Jennifer Lawrence": "Public figure",
    "Will Smith": "Public figure",
    "Keanu Reeves": "Public figure",
    "Jeffery Epstein": "Public figure",
    "MrBeast": "Public figure",
    "KSI": "Public figure",
    "Logan Paul": "Public figure",
    "IShowSpeed": "Public figure",
    "Sidemen": "Public figure"
  },
  "Movies & TV": {
    "Breaking Bad": "Entertainment",
    "Ove Sundberg": "Entertainment",
    "Game of Thrones": "Entertainment",
    "Friends": "Entertainment",
    "The Office": "Entertainment",
    "Stranger Things": "Entertainment",
    "Harry Potter": "Entertainment",
    "Star Wars": "Entertainment",
    "Arrested Development": "Entertainment",
    "The Lion King": "Entertainment",
    "Titanic": "Entertainment",
    "Inception": "Entertainment",
    "The Dark Knight": "Entertainment",
    "Forrest Gump": "Entertainment",
    "Shrek": "Entertainment",
    "Avatar": "Entertainment",
    "Frozen": "Entertainment",
    "Toy Story": "Entertainment",
    "The Simpsons": "Entertainment",
    "Interstellar": "Entertainment",
    "The Matrix": "Entertainment",
    "Jurassic Park": "Entertainment",
    "Lord of the Rings": "Entertainment",
    "The Hobbit": "Entertainment",
    "The Hunger Games": "Entertainment",
    "Pirates of the Caribbean": "Entertainment",
    "Gladiator": "Entertainment",
    "Mission Impossible": "Entertainment",
    "Fast & Furious": "Entertainment",
    "Black Panther": "Entertainment",
    "Guardians of the Galaxy": "Entertainment",
    "The Avengers": "Entertainment",
    "Deadpool": "Entertainment",
    "The Walking Dead": "Entertainment",
    "Peaky Blinders": "Entertainment",
    "Narcos": "Entertainment",
    "Money Heist": "Entertainment",
    "The Crown": "Entertainment",
    "Wednesday": "Entertainment",
    "Squid Game": "Entertainment",
    "How I Met Your Mother": "Entertainment",
    "Brooklyn Nine-Nine": "Entertainment",
    "Family Guy": "Entertainment",
    "South Park": "Entertainment",
    "Rick and Morty": "Entertainment",
    "Minions": "Entertainment",
    "Cars": "Entertainment",
    "Modern Family": "Entertainment",
    "Störst av allt": "Entertainment",
    "Solsidan": "Entertainment",
    "Darth Vader": "Entertainment",
    "Yoda": "Entertainment",
    "Spider-Man": "Entertainment",
    "Batman": "Entertainment",
    "Joker": "Entertainment",
    "Iron Man": "Entertainment",
    "Walter White": "Entertainment",
    "Homer Simpson": "Entertainment",
    "Fredrik Schiller": "Entertainment"
  },
  "Professions": {
    "Police Officer": "Work role",
    "Firefighter": "Work role",
    "Security Guard": "Work role",
    "Bouncer": "Work role",
    "Doctor": "Work role",
    "Nurse": "Work role",
    "Surgeon": "Work role",
    "Dentist": "Work role",
    "Psychologist": "Work role",
    "Preschool Teacher": "Work role",
    "High School Teacher": "Work role",
    "Private Tutor": "Work role",
    "University Professor": "Work role",
    "McDonalds Cashier": "Work role",
    "Office Worker": "Work role",
    "Programmer": "Work role",
    "Electrician": "Work role",
    "Plumber": "Work role",
    "Carpenter": "Work role",
    "Construction Worker": "Work role",
    "Warehouse Worker": "Work role",
    "Delivery Driver": "Work role",
    "Taxi Driver": "Work role",
    "Truck Driver": "Work role",
    "Store Clerk": "Work role",
    "Cashier": "Work role",
    "Barista": "Work role",
    "Waiter": "Work role",
    "Bartender": "Work role",
    "Chef": "Work role",
    "DJ": "Work role",
    "Musician": "Work role",
    "Photographer": "Work role",
    "Actor": "Work role",
    "Journalist": "Work role",
    "Airline Pilot": "Work role",
    "Flight Attendant": "Work role",
    "Personal Trainer": "Work role",
    "Physiotherapist": "Work role",
    "Hair Stylist": "Work role",
    "Makeup Artist": "Work role",
    "Real Estate Agent": "Work role",
    "Car Salesperson": "Work role",
    "Streamer": "Work role",
    "YouTuber": "Work role",
    "TikTok Creator": "Work role",
    "Influencer": "Work role",
    "Professional Gamer": "Work role",
    "Entrepreneur": "Work role"
  },
  "Objects": {
    "Phone": "Everyday item",
    "Snus": "Everyday item",
    "Laptop": "Everyday item",
    "AirPods": "Everyday item",
    "Charger": "Everyday item",
    "Powerbank": "Everyday item",
    "Wallet": "Everyday item",
    "Keys": "Everyday item",
    "Backpack": "Everyday item",
    "BankID": "Everyday item",
    "Swish": "Everyday item",
    "Coffee Mug": "Everyday item",
    "Water Bottle": "Everyday item",
    "Sofa": "Everyday item",
    "Bed": "Everyday item",
    "Mirror": "Everyday item",
    "Lamp": "Everyday item",
    "TV Remote": "Everyday item",
    "PlayStation Controller": "Everyday item",
    "Toothbrush": "Everyday item",
    "Shampoo": "Everyday item",
    "Perfume": "Everyday item",
    "Umbrella": "Everyday item",
    "Suitcase": "Everyday item",
    "Football": "Everyday item",
    "Tennis Racket": "Everyday item",
    "Dice": "Everyday item",
    "Playing Cards": "Everyday item",
    "Skis": "Everyday item",
    "Snowboard": "Everyday item",
    "Bicycle": "Everyday item",
    "Scooter": "Everyday item",
    "Credit Card": "Everyday item",
    "Passport": "Everyday item",
    "Driver’s License": "Everyday item",
    "Condom": "Everyday item",
    "Lipstick": "Everyday item",
    "Makeup Bag": "Everyday item",
    "Protein Shake": "Everyday item",
    "Energy Drink": "Everyday item",
    "UNO Cards": "Everyday item",
    "Monopoly": "Everyday item",
    "Beer Bottle": "Everyday item"
  },
  "Companies": {
    "IKEA": "Brand",
    "Systembolaget": "Brand",
    "Spotify": "Brand",
    "Volvo": "Brand",
    "ICA": "Brand",
    "Apoteket": "Brand",
    "Klarna": "Brand",
    "Swish": "Brand",
    "Max Burgers": "Brand",
    "SAS": "Brand",
    "PostNord": "Brand",
    "Northvolt": "Brand",
    "Pepsi": "Brand",
    "Coca-Cola": "Brand",
    "Heineken": "Brand",
    "Absolut Vodka": "Brand",
    "Red Bull": "Brand",
    "Ben & Jerry’s": "Brand",
    "Apple": "Brand",
    "Google": "Brand",
    "Microsoft": "Brand",
    "Amazon": "Brand",
    "Netflix": "Brand",
    "YouTube": "Brand",
    "TikTok": "Brand",
    "Instagram": "Brand",
    "Snapchat": "Brand",
    "Uber": "Brand",
    "Airbnb": "Brand",
    "Tesla": "Brand",
    "H&M": "Brand",
    "Zara": "Brand",
    "Nike": "Brand",
    "Adidas": "Brand",
    "Shein": "Brand",
    "Zalando": "Brand",
    "New Balance": "Brand",
    "McDonald's": "Brand",
    "Burger King": "Brand",
    "Starbucks": "Brand"
  }
};
