export const HINTS_PREDEFINED_CUSTOM = {
  "Famous cities": {
    "Berlin": "Place",
    "Vancouver": "Place",
    "Phuket": "Place",
    "Brasília": "Place",
    "Canberra": "Place",
    "Copenhagen": "Place",
    "Helsinki": "Place",
    "London": "Place",
    "Madrid": "Place",
    "Oslo": "Place",
    "Ottawa": "Place",
    "Paris": "Place",
    "Rome": "Place",
    "Stockholm": "Place",
    "Tokyo": "Place",
    "Washington D.C.": "Place",
    "Beijing": "Place",
    "Reykjavik": "Place",
    "Dublin": "Place",
    "Warsaw": "Place",
    "Prague": "Place",
    "Vienna": "Place",
    "Budapest": "Place",
    "Athens": "Place",
    "Lisbon": "Place",
    "Bern": "Place",
    "Brussels": "Place",
    "Ankara": "Place",
    "Cairo": "Place",
    "Bangkok": "Place",
    "Seoul": "Place",
    "New Delhi": "Place",
    "Mexico City": "Place",
    "Buenos Aires": "Place",
    "Milano": "Place",
    "Göteborg": "Place",
    "Malmö": "Place",
    "Uppsala": "Place",
    "Åre": "Place",
    "Barcelona": "Place",
    "Amsterdam": "Place",
    "Zurich": "Place",
    "Munich": "Place",
    "Hamburg": "Place",
    "Frankfurt": "Place",
    "New York": "Place",
    "Los Angeles": "Place",
    "Miami": "Place",
    "Las Vegas": "Place",
    "Chicago": "Place",
    "San Francisco": "Place",
    "Boston": "Place",
    "Toronto": "Place",
    "Dubai": "Place",
    "Abu Dhabi": "Place",
    "Doha": "Place",
    "Singapore": "Place",
    "Hong Kong": "Place",
    "Sydney": "Place",
    "Rio de Janeiro": "Place",
    "Cape Town": "Place",
    "Marrakech": "Place",
    "Shanghai": "Place",
    "Kyoto": "Place",
    "Osaka": "Place",
    "Bali": "Place",
    "Maldives": "Place",
    "Istanbul": "Place",
    "Ibiza": "Place",
    "Monaco": "Place",
    "Nice": "Place",
    "Edinburgh": "Place",
    "Manchester": "Place",
    "Val d'Isere": "Place",
    "Zermatt": "Place",
    "Chamonix": "Place"
  },
  "Famous landmarks": {
    "Eiffel Tower": "Place",
    "Big Ben": "Place",
    "Colosseum": "Place",
    "Statue of Liberty": "Place",
    "Golden Gate Bridge": "Place",
    "Mount Rushmore": "Place",
    "Great Wall of China": "Place",
    "Taj Mahal": "Place",
    "Petra": "Place",
    "Angkor Wat": "Place",
    "Machu Picchu": "Place",
    "Christ the Redeemer": "Place",
    "Sydney Opera House": "Place",
    "Burj Khalifa": "Place",
    "Stonehenge": "Place",
    "Turning Torso": "Place",
    "Vasa Museum": "Place",
    "Gamla Stan": "Place",
    "Stockholm City Hall": "Place",
    "Öresund Bridge": "Place",
    "Icehotel Jukkasjärvi": "Place",
    "Kalmar Castle": "Place",
    "Uppsala Cathedral": "Place",
    "Brandenburg Gate": "Place",
    "Empire State Building": "Place",
    "Sagrada Família": "Place",
    "Acropolis": "Place",
    "Niagara Falls": "Place"
  },
  "Swedish celebrities": {
    "Felix Herngren": "Public figure",
    "JLC": "Public figure",
    "Loreen": "Public figure",
    "Avicii": "Public figure",
    "Zlatan Ibrahimovic": "Public figure",
    "Björn Borg": "Public figure",
    "Ingemar Stenmark": "Public figure",
    "Henrik Lundqvist": "Public figure",
    "Sarah Sjöström": "Public figure",
    "Armand Duplantis": "Public figure",
    "Max Martin": "Public figure",
    "Robyn": "Public figure",
    "Håkan Hellström": "Public figure",
    "Veronica Maggio": "Public figure",
    "Carola Häggkvist": "Public figure",
    "Petter": "Public figure",
    "Måns Zelmerlöw": "Public figure",
    "Alicia Vikander": "Public figure",
    "Alexander Skarsgård": "Public figure",
    "Stellan Skarsgård": "Public figure",
    "Carl XVI Gustav": "Public figure",
    "Tove Lo": "Public figure",
    "Lykke Li": "Public figure",
    "PewDiePie": "Public figure",
    "Notch": "Public figure",
    "Markoolio": "Public figure",
    "Truls Möregårdh": "Public figure",
    "Stefan Löfven": "Public figure",
    "Jimmie Åkesson": "Public figure",
    "Magdalena Andersson": "Public figure",
    "Ulf Kristersson": "Public figure",
    "Fredrik Reinfeldt": "Public figure",
    "Benjamin Ingrosso": "Public figure",
    "Cornelia Jakobs": "Public figure",
    "David Batra": "Public figure",
    "Petra Mede": "Public figure",
    "Zara Larsson": "Public figure",
    "HOV1": "Public figure",
    "Bolaget": "Public figure",
    "Messiah Hallberg": "Public figure",
    "Tony Irving": "Public figure",
    "David Hellenius": "Public figure",
    "Pernilla Wahlgren": "Public figure",
    "Henrik Dorsin": "Public figure",
    "Tusse": "Public figure",
    "Jonas Andersson (RMM)": "Public figure",
    "Johan Rheborg": "Public figure",
    "Robert Gustafsson": "Public figure",
    "Bianca Ingrosso": "Public figure",
    "Ebba Busch": "Public figure",
    "Yung Lean": "Public figure",
    "Samir Badran": "Public figure",
    "Viktor Frisk": "Public figure",
    "Paow": "Public figure",
    "Peter Stormare": "Public figure",
    "Arga snickaren": "Public figure",
    "John Lundvik": "Public figure",
    "Eric Saade": "Public figure",
    "Lotta Schelin": "Public figure",
    "Anis Don Demina": "Public figure",
    "Dermot Clemenger": "Public figure",
    "Alexander Ernstberger": "Public figure",
    "Gunilla Persson": "Public figure",
    "Fröken Snusk": "Public figure",
    "Pontus Rasmusson": "Public figure",
    "Edvin Törnblom": "Public figure",
    "Johanna Nordström": "Public figure",
    "Rickard Olsson": "Public figure",
    "Isabella Löwengrip": "Public figure",
    "Paolo Roberto": "Public figure",
    "Maria Montazami": "Public figure",
    "Leif GW Persson": "Public figure",
    "Jan Emanuel": "Public figure"
  },
  "Swedish influencers": {
    "Bianca Ingrosso": "Public figure",
    "Therese Lindgren": "Public figure",
    "Johanna Nordström": "Public figure",
    "Joakim Lundell": "Public figure",
    "Jonna Lundell": "Public figure",
    "Matilda Djerf": "Public figure",
    "Alice Stenlöf": "Public figure",
    "Margaux Dietz": "Public figure",
    "Clara Henry": "Public figure",
    "Anis Don Demina": "Public figure",
    "Keyyo": "Public figure",
    "Jon Olsson": "Public figure",
    "Lovisa Barkman": "Public figure",
    "Lovisa Worge": "Public figure",
    "Hanna Schönberg": "Public figure",
    "Hanna Friberg": "Public figure",
    "Wilma Holmqvist": "Public figure",
    "Isa Östling": "Public figure",
    "Antonija Mandir": "Public figure",
    "IJustWantToBeCool": "Public figure",
    "Edvin Törnblom": "Public figure",
    "JLC": "Public figure",
    "Random Making Movies": "Public figure",
    "STHLM Panda": "Public figure",
    "Filip Dikmen": "Public figure",
    "Hampus Hedström": "Public figure",
    "Tan by Klara": "Public figure",
    "Emelie Lindmark": "Public figure",
    "Sofie Karlstad": "Public figure",
    "Amilia Stapelfeldt": "Public figure",
    "Christofer Westerlund": "Public figure",
    "Isabella Löwengrip": "Public figure",
    "Kenza Zouiten": "Public figure",
    "Sofie Fahrman": "Public figure",
    "Matilda Smedius": "Public figure"
  },
  "Places in Sweden": {
    "Stockholm": "Geography",
    "Boden": "Geography",
    "Lidingö": "Geography",
    "Visby": "Geography",
    "Nacka": "Geography",
    "Bromma": "Geography",
    "Rinkeby": "Geography",
    "Tensta": "Geography",
    "Södertälje": "Geography",
    "Täby": "Geography",
    "Sollentuna": "Geography",
    "Upplands Väsby": "Geography",
    "Huddinge": "Geography",
    "Nynäshamn": "Geography",
    "Västerås": "Geography",
    "Uppsala": "Geography",
    "Strängnäs": "Geography",
    "Enköping": "Geography",
    "Norrtälje": "Geography",
    "Örebro": "Geography",
    "Eskilstuna": "Geography",
    "Linköping": "Geography",
    "Nyköping": "Geography",
    "Västervik": "Geography",
    "Kalmar": "Geography",
    "Karlskrona": "Geography",
    "Halmstad": "Geography",
    "Helsingborg": "Geography",
    "Lund": "Geography",
    "Malmö": "Geography",
    "Ystad": "Geography",
    "Trelleborg": "Geography",
    "Göteborg": "Geography",
    "Båstad": "Geography",
    "Falsterbo": "Geography",
    "Örkeljunga": "Geography"
  },
  "Stranger Things": {
    "Eleven": "Entertainment",
    "Mike Wheeler": "Entertainment",
    "Dustin Henderson": "Entertainment",
    "Lucas Sinclair": "Entertainment",
    "Will Byers": "Entertainment",
    "Max Mayfield": "Entertainment",
    "Hopper": "Entertainment",
    "Joyce Byers": "Entertainment",
    "Vecna": "Entertainment",
    "Mind Flayer": "Entertainment",
    "Demogorgon": "Entertainment",
    "Demodog": "Entertainment",
    "Upside Down": "Entertainment",
    "Hawkins": "Entertainment",
    "Starcourt Mall": "Entertainment",
    "Eggo waffles": "Entertainment",
    "Hellfire Club": "Entertainment",
    "Eddie Munson": "Entertainment",
    "Season 1": "Entertainment",
    "Christmas lights": "Entertainment",
    "Season 2": "Entertainment",
    "Season 3": "Entertainment",
    "Final Season": "Entertainment"
  },
  "The Office": {
    "Michael Scott": "Entertainment",
    "Dwight Schrute": "Entertainment",
    "Jim Halpert": "Entertainment",
    "Pam Beesly": "Entertainment",
    "Andy Bernard": "Entertainment",
    "Stanley Hudson": "Entertainment",
    "Kevin Malone": "Entertainment",
    "Angela Martin": "Entertainment",
    "Oscar Martinez": "Entertainment",
    "Creed Bratton": "Entertainment",
    "Toby Flenderson": "Entertainment",
    "Todd Packer": "Entertainment",
    "Jan Levinson": "Entertainment",
    "Dunder Mifflin": "Entertainment",
    "Scranton": "Entertainment",
    "World’s Best Boss": "Entertainment",
    "Pranks": "Entertainment",
    "Beets": "Entertainment",
    "Fun run": "Entertainment",
    "Phyllis Vance": "Entertainment",
    "Bob Vance": "Entertainment",
    "Ryan the temp": "Entertainment",
    "Kelly Kapoor": "Entertainment",
    "Prison Mike": "Entertainment",
    "That’s what she said": "Entertainment",
    "Office Olympics": "Entertainment",
    "Pretzel Day": "Entertainment",
    "Conference Room": "Entertainment",
    "Dinner Party": "Entertainment",
    "The warehouse": "Entertainment"
  },
  "Friends": {
    "Rachel Green": "Entertainment",
    "Ross Geller": "Entertainment",
    "Monica Geller": "Entertainment",
    "Chandler Bing": "Entertainment",
    "Joey Tribbiani": "Entertainment",
    "Phoebe Buffay": "Entertainment",
    "Janice": "Entertainment",
    "Central Perk": "Entertainment",
    "Smelly Cat": "Entertainment",
    "Pivot": "Entertainment",
    "We were on a break": "Entertainment",
    "Apartment": "Entertainment",
    "Thanksgiving": "Entertainment",
    "Coffee": "Entertainment",
    "New York": "Entertainment",
    "Gunther": "Entertainment",
    "The Couch": "Entertainment",
    "Wedding in London": "Entertainment",
    "Holiday Armadillo": "Entertainment"
  },
  "Breaking Bad": {
    "Walter White": "Entertainment",
    "Jesse Pinkman": "Entertainment",
    "Saul Goodman": "Entertainment",
    "Skyler White": "Entertainment",
    "Hank Schrader": "Entertainment",
    "Gus Fring": "Entertainment",
    "Mike Ehrmantraut": "Entertainment",
    "Heisenberg": "Entertainment",
    "Los Pollos Hermanos": "Entertainment",
    "Blue meth": "Entertainment",
    "RV": "Entertainment",
    "DEA": "Entertainment",
    "Chemistry": "Entertainment",
    "Albuquerque": "Entertainment",
    "Say my name": "Entertainment",
    "Better Call Saul": "Entertainment",
    "Money barrel": "Entertainment",
    "Car wash": "Entertainment"
  },
  "Game of Thrones": {
    "Jon Snow": "Entertainment",
    "Daenerys Targaryen": "Entertainment",
    "Tyrion Lannister": "Entertainment",
    "Arya Stark": "Entertainment",
    "Sansa Stark": "Entertainment",
    "Cersei Lannister": "Entertainment",
    "Jaime Lannister": "Entertainment",
    "Night King": "Entertainment",
    "White Walkers": "Entertainment",
    "Dragons": "Entertainment",
    "Winterfell": "Entertainment",
    "King’s Landing": "Entertainment",
    "Iron Throne": "Entertainment",
    "House Stark": "Entertainment",
    "House Lannister": "Entertainment",
    "The Wall": "Entertainment",
    "Red Wedding": "Entertainment",
    "Mother of Dragons": "Entertainment"
  },
  "Disney": {
    "Mickey Mouse": "Entertainment",
    "Donald Duck": "Entertainment",
    "Goofy": "Entertainment",
    "Elsa": "Entertainment",
    "Anna": "Entertainment",
    "Simba": "Entertainment",
    "Ariel": "Entertainment",
    "Belle": "Entertainment",
    "Aladdin": "Entertainment",
    "Genie": "Entertainment",
    "Buzz Lightyear": "Entertainment",
    "Woody": "Entertainment",
    "Cinderella": "Entertainment",
    "Snow White": "Entertainment",
    "Stitch": "Entertainment",
    "Moana": "Entertainment",
    "Mulan": "Entertainment",
    "Rapunzel": "Entertainment",
    "Olaf": "Entertainment",
    "Peter Pan": "Entertainment",
    "Tinker Bell": "Entertainment"
  },
  "Harry Potter": {
    "Harry Potter": "Entertainment",
    "Hermione Granger": "Entertainment",
    "Ron Weasley": "Entertainment",
    "Albus Dumbledore": "Entertainment",
    "Severus Snape": "Entertainment",
    "Voldemort": "Entertainment",
    "Draco Malfoy": "Entertainment",
    "Hagrid": "Entertainment",
    "Sirius Black": "Entertainment",
    "Hogwarts": "Entertainment",
    "Dudley": "Entertainment",
    "Cedric Diggory": "Entertainment",
    "Cho Chang": "Entertainment",
    "Gryffindor": "Entertainment",
    "Slytherin": "Entertainment",
    "Hufflepuff": "Entertainment",
    "Ravenclaw": "Entertainment",
    "Quidditch": "Entertainment",
    "Remus Lupin": "Entertainment",
    "Hedwig": "Entertainment",
    "Dobby": "Entertainment",
    "Azkaban": "Entertainment",
    "The Sorting Hat": "Entertainment",
    "Expelliarmus": "Entertainment",
    "The half blood prine": "Entertainment",
    "Triwizard tournament": "Entertainment"
  },
  "Marvel Cinematic Universe": {
    "Iron Man": "Entertainment",
    "Captain America": "Entertainment",
    "Thor": "Entertainment",
    "Hulk": "Entertainment",
    "Black Widow": "Entertainment",
    "Hawkeye": "Entertainment",
    "Spider-Man": "Entertainment",
    "Doctor Strange": "Entertainment",
    "Black Panther": "Entertainment",
    "Scarlet Witch": "Entertainment",
    "Loki": "Entertainment",
    "Ant-Man": "Entertainment",
    "Guardians of the Galaxy": "Entertainment",
    "Avengers": "Entertainment",
    "Thanos": "Entertainment",
    "Infinity Stones": "Entertainment",
    "Wakanda": "Entertainment",
    "Nick Fury": "Entertainment",
    "Deadpool": "Entertainment"
  },
  "Animals": {
    "Dog": "Living creature",
    "Cat": "Living creature",
    "Horse": "Living creature",
    "Rabbit": "Living creature",
    "Bear": "Living creature",
    "Wolf": "Living creature",
    "Lion": "Living creature",
    "Tiger": "Living creature",
    "Elephant": "Living creature",
    "Giraffe": "Living creature",
    "Zebra": "Living creature",
    "Panda": "Living creature",
    "Kangaroo": "Living creature",
    "Dolphin": "Living creature",
    "Eagle": "Living creature",
    "Shark": "Living creature",
    "Whale": "Living creature",
    "Penguin": "Living creature",
    "Fox": "Living creature",
    "Owl": "Living creature",
    "Monkey": "Living creature",
    "Moose": "Living creature"
  },
  "School subjects": {
    "Mathematics": "Education",
    "English": "Education",
    "History": "Education",
    "Geography": "Education",
    "Biology": "Education",
    "Chemistry": "Education",
    "Physics": "Education",
    "Computer Science": "Education",
    "Economics": "Education",
    "Civics": "Education",
    "Psychology": "Education",
    "Philosophy": "Education",
    "Art": "Education",
    "Music": "Education",
    "Physical Education": "Education",
    "Drama": "Education",
    "Religion": "Education",
    "French": "Education",
    "Spanish": "Education"
  },
  "Sports": {
    "Football": "Athletic activity",
    "Basketball": "Athletic activity",
    "Tennis": "Athletic activity",
    "Hockey": "Athletic activity",
    "Ice hockey": "Athletic activity",
    "Baseball": "Athletic activity",
    "Cricket": "Athletic activity",
    "Rugby": "Athletic activity",
    "Golf": "Athletic activity",
    "Athletics": "Athletic activity",
    "Running": "Athletic activity",
    "Swimming": "Athletic activity",
    "Volleyball": "Athletic activity",
    "Badminton": "Athletic activity",
    "Boxing": "Athletic activity",
    "Martial arts": "Athletic activity",
    "Cycling": "Athletic activity",
    "Skiing": "Athletic activity",
    "Snowboarding": "Athletic activity",
    "Ice skating": "Athletic activity",
    "Figure skating": "Athletic activity",
    "Roller skating": "Athletic activity",
    "Motorsport": "Athletic activity",
    "Disc golf": "Athletic activity",
    "Bowling": "Athletic activity",
    "Handball": "Athletic activity",
    "Padel": "Athletic activity",
    "Ping pong": "Athletic activity",
    "Pool": "Athletic activity",
    "Darts": "Athletic activity",
    "Surfing": "Athletic activity",
    "Wind surfing": "Athletic activity",
    "Water skiing": "Athletic activity",
    "Jet skiing": "Athletic activity",
    "Karate": "Athletic activity",
    "Taekwondo": "Athletic activity",
    "Judo": "Athletic activity",
    "Kickboxing": "Athletic activity",
    "Sumo wrestling": "Athletic activity",
    "Fencing": "Athletic activity",
    "Gymnastics": "Athletic activity",
    "Weight lifting": "Athletic activity",
    "Archery": "Athletic activity",
    "Fishing": "Athletic activity",
    "Horse racing": "Athletic activity",
    "Rock climbing": "Athletic activity",
    "Scuba diving": "Athletic activity",
    "Skateboarding": "Athletic activity",
    "Street hockey": "Athletic activity",
    "Sky diving": "Athletic activity",
    "Hang gliding": "Athletic activity",
    "Bungee jumping": "Athletic activity",
    "Chess": "Athletic activity",
    "E-sports": "Athletic activity"
  },
  "Athletes": {
    "Lionel Messi": "Sports person",
    "Sarah Sjöström": "Sports person",
    "Shaquille O'Neal": "Sports person",
    "Cristiano Ronaldo": "Sports person",
    "Neymar": "Sports person",
    "Diego Maradona": "Sports person",
    "Pelé": "Sports person",
    "Ronaldinho": "Sports person",
    "David Beckham": "Sports person",
    "LeBron James": "Sports person",
    "Michael Jordan": "Sports person",
    "Kobe Bryant": "Sports person",
    "Kevin Durant": "Sports person",
    "Tom Brady": "Sports person",
    "Babe Ruth": "Sports person",
    "Roger Federer": "Sports person",
    "Serena Williams": "Sports person",
    "Naomi Osaka": "Sports person",
    "Tiger Woods": "Sports person",
    "Muhammad Ali": "Sports person",
    "Mike Tyson": "Sports person",
    "Floyd Mayweather": "Sports person",
    "Anthony Joshua": "Sports person",
    "Conor McGregor": "Sports person",
    "Khabib Nurmagomedov": "Sports person",
    "Jon Jones": "Sports person",
    "Georges St-Pierre": "Sports person",
    "Ronda Rousey": "Sports person",
    "Amanda Nunes": "Sports person",
    "Usain Bolt": "Sports person",
    "Michael Phelps": "Sports person",
    "Lewis Hamilton": "Sports person",
    "Max Verstappen": "Sports person",
    "Michael Schumacher": "Sports person",
    "Arnold Schwarzenegger": "Sports person",
    "The Rock": "Sports person",
    "Zlatan Ibrahimović": "Sports person",
    "Björn Borg": "Sports person",
    "Armand Duplantis": "Sports person",
    "Henrik Lundqvist": "Sports person",
    "Ingemar Stenmark": "Sports person",
    "Truls Möregårdh": "Sports person"
  },
  "Allsvenskan teams": {
    "AIK": "Sports club",
    "Djurgårdens IF": "Sports club",
    "Hammarby IF": "Sports club",
    "IFK Göteborg": "Sports club",
    "Malmö FF": "Sports club",
    "IF Elfsborg": "Sports club",
    "BK Häcken": "Sports club",
    "IFK Norrköping": "Sports club",
    "Kalmar FF": "Sports club",
    "IK Sirius": "Sports club",
    "Halmstads BK": "Sports club",
    "Degerfors IF": "Sports club",
    "Mjällby AIF": "Sports club",
    "Varbergs BoIS": "Sports club",
    "IF Brommapojkarna": "Sports club",
    "Örebro SK": "Sports club"
  },
  "Premier League teams": {
    "Manchester United": "Sports club",
    "Manchester City": "Sports club",
    "Liverpool": "Sports club",
    "Arsenal": "Sports club",
    "Chelsea": "Sports club",
    "Tottenham Hotspur": "Sports club",
    "Newcastle United": "Sports club",
    "Aston Villa": "Sports club",
    "West Ham United": "Sports club",
    "Everton": "Sports club",
    "Brighton": "Sports club",
    "Wolverhampton": "Sports club",
    "Crystal Palace": "Sports club",
    "Brentford": "Sports club",
    "Nottingham Forest": "Sports club",
    "Leicester City": "Sports club"
  },
  "Tennis players": {
    "Roger Federer": "Sports person",
    "Rafael Nadal": "Sports person",
    "Novak Djokovic": "Sports person",
    "Andy Murray": "Sports person",
    "Carlos Alcaraz": "Sports person",
    "Daniil Medvedev": "Sports person",
    "Jannik Sinner": "Sports person",
    "Alexander Zverev": "Sports person",
    "Stefanos Tsitsipas": "Sports person",
    "Casper Ruud": "Sports person",
    "Serena Williams": "Sports person",
    "Venus Williams": "Sports person",
    "Iga Świątek": "Sports person",
    "Naomi Osaka": "Sports person",
    "Maria Sharapova": "Sports person",
    "Björn Borg": "Sports person"
  },
  "Beer brands": {
    "Heineken": "Brand",
    "Corona": "Brand",
    "Mariestads": "Brand",
    "Budweiser": "Brand",
    "Guinness": "Brand",
    "Carlsberg": "Brand",
    "Stella Artois": "Brand",
    "Peroni": "Brand",
    "Asahi": "Brand",
    "Modelo": "Brand",
    "Kronenbourg": "Brand",
    "Beck’s": "Brand",
    "Coors": "Brand",
    "Miller": "Brand",
    "Samuel Adams": "Brand",
    "Pripps Blå": "Brand",
    "Norrlands Guld": "Brand",
    "Falcon": "Brand",
    "Spendrups": "Brand",
    "Åbro": "Brand",
    "Sofiero": "Brand",
    "Eriksberg": "Brand",
    "Lapin Kulta": "Brand"
  },
  "Car brands": {
    "Toyota": "Brand",
    "Volkswagen": "Brand",
    "Porsche": "Brand",
    "BMW": "Brand",
    "Mercedes-Benz": "Brand",
    "Audi": "Brand",
    "Volvo": "Brand",
    "Ford": "Brand",
    "Chevrolet": "Brand",
    "Honda": "Brand",
    "Hyundai": "Brand",
    "Kia": "Brand",
    "Nissan": "Brand",
    "Mazda": "Brand",
    "Tesla": "Brand",
    "Ferrari": "Brand",
    "Lamborghini": "Brand",
    "Koenigsegg": "Brand"
  },
  "Clothing brands": {
    "Nike": "Brand",
    "Armani": "Brand",
    "New Balance": "Brand",
    "Adidas": "Brand",
    "Puma": "Brand",
    "H&M": "Brand",
    "Zara": "Brand",
    "Uniqlo": "Brand",
    "Levi’s": "Brand",
    "Ralph Lauren": "Brand",
    "Tommy Hilfiger": "Brand",
    "Calvin Klein": "Brand",
    "Patagonia": "Brand",
    "Supreme": "Brand",
    "Gucci": "Brand",
    "Prada": "Brand",
    "Balenciaga": "Brand"
  },
  "Melodifestivalen": {
    "Carola": "Music",
    "Loreen": "Music",
    "Måns Zelmerlöw": "Music",
    "Charlotte Perrelli": "Music",
    "The Ark": "Music",
    "Robin Bengtsson": "Music",
    "Benjamin Ingrosso": "Music",
    "Anna Bergendahl": "Music",
    "Eric Saade": "Music",
    "Sanna Nielsen": "Music",
    "John Lundvik": "Music",
    "Cornelia Jakobs": "Music",
    "Tusse": "Music",
    "Arvingarna": "Music",
    "Anders Bagge": "Music",
    "Danny Saucedo": "Music",
    "Alcazar": "Music",
    "The Mamas": "Music",
    "Jill Johnson": "Music",
    "Lisa Ajax": "Music",
    "Nano": "Music",
    "Anna Book": "Music",
    "Jessica Andersson": "Music",
    "Jon Henrik Fjällgren": "Music"
  },
  "Popular artists": {
    "Taylor Swift": "Music",
    "Ed Sheeran": "Music",
    "Beyoncé": "Music",
    "Drake": "Music",
    "Ariana Grande": "Music",
    "Billie Eilish": "Music",
    "The Weeknd": "Music",
    "Justin Bieber": "Music",
    "Rihanna": "Music",
    "Adele": "Music",
    "Bruno Mars": "Music",
    "Dua Lipa": "Music",
    "Post Malone": "Music",
    "Lady Gaga": "Music",
    "Harry Styles": "Music",
    "Olivia Rodrigo": "Music",
    "Shakira": "Music",
    "Katy Perry": "Music",
    "SZA": "Music",
    "Travis Scott": "Music",
    "Doja Cat": "Music",
    "Nicki Minaj": "Music",
    "Shawn Mendes": "Music",
    "Miley Cyrus": "Music",
    "Elton John": "Music",
    "Michael Jackson": "Music",
    "Madonna": "Music",
    "Bad Bunny": "Music"
  },
  "Popular bands": {
    "Coldplay": "Music",
    "Imagine Dragons": "Music",
    "Maroon 5": "Music",
    "OneRepublic": "Music",
    "Red Hot Chili Peppers": "Music",
    "ABBA": "Music",
    "Queen": "Music",
    "Linkin Park": "Music",
    "Green Day": "Music",
    "U2": "Music",
    "The Rolling Stones": "Music",
    "Metallica": "Music",
    "Arctic Monkeys": "Music",
    "Foo Fighters": "Music",
    "Nirvana": "Music",
    "The Beatles": "Music",
    "Oasis": "Music",
    "Blink-182": "Music",
    "The Killers": "Music",
    "Kings of Leon": "Music",
    "Bon Jovi": "Music",
    "Guns N’ Roses": "Music",
    "The Police": "Music"
  },
  "Pre 2000’s Hits": {
    "Dancing Queen (ABBA)": "Music",
    "Bohemian Rhapsody (Queen)": "Music",
    "Billie Jean (Michael Jackson)": "Music",
    "Like a Prayer (Madonna)": "Music",
    "Smells Like Teen Spirit (Nirvana)": "Music",
    "Livin’ on a Prayer (Bon Jovi)": "Music",
    "Take On Me (a-ha)": "Music",
    "Sweet Child O’ Mine (Guns N’ Roses)": "Music",
    "I Will Survive (Gloria Gaynor)": "Music",
    "Every Breath You Take (The Police)": "Music",
    "Thriller (Michael Jackson)": "Music",
    "Hotel California (Eagles)": "Music",
    "Don’t Stop Believin’ (Journey)": "Music",
    "Girls Just Want to Have Fun (Cyndi Lauper)": "Music",
    "Beat It (Michael Jackson)": "Music",
    "Eye of the Tiger (Survivor)": "Music",
    "Summer of ’69 (Bryan Adams)": "Music",
    "Another Brick in the Wall (Pink Floyd)": "Music",
    "Sweet Dreams (Are Made of This) (Eurythmics)": "Music",
    "With or Without You (U2)": "Music",
    "Careless Whisper (George Michael)": "Music"
  },
  "2000’s Hits": {
    "Poker Face (Lady Gaga)": "Music",
    "Umbrella (Rihanna)": "Music",
    "Crazy in Love (Beyoncé)": "Music",
    "Hey Ya! (Outkast)": "Music",
    "Mr. Brightside (The Killers)": "Music",
    "Hips Don’t Lie (Shakira)": "Music",
    "Yeah! (Usher)": "Music",
    "Since U Been Gone (Kelly Clarkson)": "Music",
    "Rolling in the Deep (Adele)": "Music",
    "Single Ladies (Beyoncé)": "Music",
    "Viva La Vida (Coldplay)": "Music",
    "Apologize (OneRepublic)": "Music",
    "Firework (Katy Perry)": "Music",
    "Tik Tok (Kesha)": "Music",
    "Clocks (Coldplay)": "Music",
    "Toxic (Britney Spears)": "Music",
    "In the End (Linkin Park)": "Music",
    "Seven Nation Army (The White Stripes)": "Music",
    "Complicated (Avril Lavigne)": "Music",
    "Low (Flo Rida)": "Music",
    "Empire State of Mind (Jay-Z)": "Music",
    "Disturbia (Rihanna)": "Music",
    "Grenade (Bruno Mars)": "Music",
    "SexyBack (Justin Timberlake)": "Music",
    "Lose Yourself (Eminem)": "Music"
  },
  "Recent hits": {
    "Blinding Lights (The Weeknd)": "Music",
    "Shape of You (Ed Sheeran)": "Music",
    "Dance Monkey (Tones and I)": "Music",
    "As It Was (Harry Styles)": "Music",
    "Levitating (Dua Lipa)": "Music",
    "Someone You Loved (Lewis Capaldi)": "Music",
    "Bad Guy (Billie Eilish)": "Music",
    "Shallow (Lady Gaga)": "Music",
    "Old Town Road (Lil Nas X)": "Music",
    "Despacito (Luis Fonsi)": "Music",
    "Sunflower (Post Malone)": "Music",
    "Drivers License (Olivia Rodrigo)": "Music",
    "Stay (The Kid LAROI)": "Music",
    "Watermelon Sugar (Harry Styles)": "Music",
    "Rockstar (Post Malone)": "Music",
    "Anti-Hero (Taylor Swift)": "Music",
    "Flowers (Miley Cyrus)": "Music",
    "Industry Baby (Lil Nas X)": "Music",
    "Montero (Lil Nas X)": "Music",
    "Heat Waves (Glass Animals)": "Music",
    "Unholy (Sam Smith)": "Music"
  },
  "Video games": {
    "Mario": "Gaming",
    "Luigi": "Gaming",
    "Princess Peach": "Gaming",
    "Bowser": "Gaming",
    "Yoshi": "Gaming",
    "Donkey Kong": "Gaming",
    "Link": "Gaming",
    "Zelda": "Gaming",
    "Pikachu": "Gaming",
    "Kirby": "Gaming",
    "Samus": "Gaming",
    "Wario": "Gaming",
    "Super Mario Bros": "Gaming",
    "The Legend of Zelda": "Gaming",
    "Pokémon": "Gaming",
    "Tetris": "Gaming",
    "Pac-Man": "Gaming",
    "Sonic the Hedgehog": "Gaming",
    "Street Fighter": "Gaming",
    "Mortal Kombat": "Gaming",
    "Minecraft": "Gaming",
    "The Sims": "Gaming",
    "Grand Theft Auto": "Gaming",
    "Call of Duty": "Gaming",
    "Halo": "Gaming",
    "FIFA": "Gaming",
    "Fortnite": "Gaming",
    "Counter-Strike": "Gaming",
    "League of Legends": "Gaming",
    "World of Warcraft": "Gaming",
    "Overwatch": "Gaming",
    "Valorant": "Gaming",
    "Red Dead Redemption": "Gaming",
    "The Last of Us": "Gaming",
    "God of War": "Gaming",
    "Assassin’s Creed": "Gaming",
    "Skyrim": "Gaming",
    "Elden Ring": "Gaming",
    "Cyberpunk 2077": "Gaming",
    "Among Us": "Gaming",
    "Roblox": "Gaming",
    "Clash of Clans": "Gaming",
    "Brawl Stars": "Gaming",
    "Animal Crossing": "Gaming",
    "Super Smash Bros": "Gaming",
    "Kratos": "Gaming",
    "Lara Croft": "Gaming",
    "Steve (Minecraft)": "Gaming",
    "Creeper": "Gaming",
    "Solid Snake": "Gaming"
  },
  "Alcoholic Beverages": {
    "Beer": "Drink",
    "Wine": "Drink",
    "Red wine": "Drink",
    "White wine": "Drink",
    "Rosé": "Drink",
    "Whiskey": "Drink",
    "Vodka": "Drink",
    "Rum": "Drink",
    "Gin": "Drink",
    "Tequila": "Drink",
    "Cider": "Drink",
    "Champagne": "Drink",
    "Cognac": "Drink",
    "Brandy": "Drink",
    "Liqueur": "Drink",
    "Absinthe": "Drink",
    "Sake": "Drink",
    "Mead": "Drink",
    "Akvavit": "Drink",
    "Snaps": "Drink",
    "Brännvin": "Drink",
    "Glögg": "Drink",
    "Aperol": "Drink"
  },
  "Food & snacks": {
    "Pizza": "Food",
    "Hamburger": "Food",
    "Cheeseburger": "Food",
    "Hot Dog": "Food",
    "Kebab": "Food",
    "Tacos": "Food",
    "Burrito": "Food",
    "Nachos": "Food",
    "Fries": "Food",
    "Chicken Nuggets": "Food",
    "Meatballs": "Food",
    "Kanelbulle": "Food",
    "Semla": "Food",
    "Smörgåstårta": "Food",
    "Prinsesstårta": "Food",
    "Gravlax": "Food",
    "Raggmunk": "Food",
    "Surströmming": "Food",
    "Knäckebröd": "Food",
    "Lussekatt": "Food",
    "Sushi": "Food",
    "Pasta": "Food",
    "Spaghetti Bolognese": "Food",
    "Lasagna": "Food",
    "Ramen": "Food",
    "Pad Thai": "Food",
    "Butter Chicken": "Food",
    "Falafel": "Food",
    "Paella": "Food",
    "Dumplings": "Food",
    "Chips": "Food",
    "Popcorn": "Food",
    "Candy": "Food",
    "Chocolate": "Food",
    "Marabou": "Food",
    "Salted Peanuts": "Food",
    "Protein Bar": "Food",
    "Energy Drink": "Food",
    "Ice Cream": "Food",
    "Ben & Jerry’s": "Food",
    "Brownie": "Food",
    "Cheesecake": "Food",
    "Cupcake": "Food",
    "Pancakes": "Food",
    "Waffles": "Food",
    "Donut": "Food",
    "Macaron": "Food",
    "Tiramisu": "Food",
    "Apple Pie": "Food",
    "Chokladboll": "Food",
    "Avocado": "Food",
    "Banana": "Food",
    "Strawberries": "Food",
    "Watermelon": "Food",
    "Salmon": "Food",
    "Steak": "Food",
    "Egg": "Food",
    "Toast": "Food",
    "Sandwich": "Food",
    "Yoghurt": "Food",
    "Coffee": "Food",
    "Cappuccino": "Food",
    "Latte": "Food",
    "Milkshake": "Food",
    "Smoothie": "Food",
    "Cola": "Food",
    "Fanta": "Food",
    "Red Bull": "Food",
    "Beer": "Food",
    "Wine": "Food"
  }
};
