export const CATEGORIES = {
  "Countries": [
    "Colombia", "Sweden", "Israel", "South Africa", "Norway", "Denmark", "Finland",
    "Germany", "France", "Spain", "Italy", "Portugal",
    "Netherlands", "Belgium", "Switzerland", "Austria",
    "United Kingdom", "Greece", "Hungary", "Romania",
    "United States", "Canada", "Mexico", "Brazil",
    "Argentina", "Chile",
    "China", "Japan", "South Korea", "India",
    "Thailand", "Vietnam", "Indonesia",
    "Turkey", "Saudi Arabia", "United Arab Emirates",
    "Egypt", "Morocco",
    "Australia", "New Zealand",
  ],
  "Cities": [
    "Bangkok", "Stockholm", "Rome", "Lidingö",
    "Göteborg", "Malmö", "Uppsala",
    "Åre", "Val-d'Isère",
    "London", "Paris", "Berlin", "Barcelona",
    "Amsterdam", "Milan", "Lisbon",
    "Prague", "Vienna", "Athens",
    "New York", "Los Angeles", "Miami",
    "Las Vegas", "San Francisco",
    "Toronto", "Mexico City",
    "Dubai", "Tokyo", "Seoul",
    "Singapore", "Hong Kong",
    "Sydney", "Rio de Janeiro", "Cape Town",
  ],
  "Celebrities": [
    "Darin", "Donald Trump", "Greta Thunberg", "Avicii", "Bianca Ingrosso", "Felix Kjellberg",
    "Zara Larsson", "Molly Sandén", "Veronica Maggio",
    "Håkan Hellström", "Therese Lindgren", "Zlatan Ibrahimović", "Armand Duplantis",
    "Ulf Kristersson", "Magdalena Andersson", "Stefan Löfven",
    "Markoolio", "Petter", "Einár", "Yasin",
    "Jonas Fagerström", "Joakim Lundell", "Matilda Djerf", "JLC",
    "IJustWantToBeCool", "RandomMakingMovies", "STHLM Panda",
    "Taylor Swift", "Rihanna", "Ariana Grande", "Billie Eilish",
    "Adele", "Ed Sheeran", "Drake", "Eminem", "Kanye West",
    "Lady Gaga", "Jennifer Lopez", "Shakira", "Justin Bieber",
    "The Weeknd", "Post Malone", "Dua Lipa", "Harry Styles", "Travis Scott",
    "Nicki Minaj", "Lil Nas X",
    "Cristiano Ronaldo", "Lionel Messi", "LeBron James", "Serena Williams",
    "Neymar", "Kylian Mbappé", "Erling Haaland", "Stephen Curry",
    "Usain Bolt", "Conor McGregor",
    "Leonardo DiCaprio", "Brad Pitt", "Tom Hanks", "Will Smith",
    "Dwayne Johnson", "Johnny Depp", "Robert Downey Jr.",
    "Ryan Gosling", "Margot Robbie", "Zendaya",
    "Timothée Chalamet", "Scarlett Johansson",
    "Elon Musk", "Barack Obama", "Joe Biden",
    "Jeff Bezos", "Mark Zuckerberg",
    "MrBeast", "Logan Paul", "KSI", "Kai Cenat", "IShowSpeed",
    "Andrew Tate", "Charlie Kirk", "Alexander Ernstberger",
  ],
  "Movies & TV": [
    "The Godfather", "Jesse Pinkman", "Yoda", "Titanic", "Inception", "The Lion King", "Avengers",
    "Breaking Bad", "Game of Thrones", "Friends", "The Office", "Stranger Things",
    "Harry Potter", "Star Wars", "Jurassic Park", "The Matrix", "Forrest Gump",
    "Pulp Fiction", "The Dark Knight", "Shrek", "Finding Nemo", "Avatar",
    "Interstellar", "Frozen", "Toy Story", "The Simpsons",
    "Peter Griffin", "Homer Simpson",
    "Darth Vader",
    "Iron Man", "Captain America", "Thor",
    "Batman", "Joker", "Superman",
    "Spider-Man", "Deadpool",
    "Voldemort",
    "Walter White",
    "Daenerys Targaryen",
  ],
  "Objects": [
    "Phone", "Laptop", "Water Bottle", "Sunglasses", "Headphones", "Charger",
    "Wallet", "Keys", "Backpack",
    "Snus", "SL Card", "BankID", "Swish",
    "Chair", "Table", "Sofa", "Bed",
    "Lamp", "Mirror", "Clock",
    "Coffee Mug", "Plate",
    "Fork", "Knife", "Spoon",
    "Apple", "Banana", "Sandwich",
    "TV Remote",
    "Shoes",
    "Book", "Pen",
    "Toothbrush", "Soap",
    "Umbrella", "Scissors", "Tape",
    "Pillow",
    "Shopping Bag", "Suitcase",
    "Ball", "Dice", "Playing Cards",
    "Candle", "Flower",
  ],
  "Companies": [
    "IKEA", "Temu", "Systembolaget", "Spotify", "Volvo",
    "ICA", "Apoteket", "H&M",
    "SL", "SAS", "PostNord",
    "Telia",
    "Klarna", "Swish",
    "Max Burgers", "McDonald's", "Burger King",
    "Sibylla", "Pressbyrån",
    "Lidl",
    "Foodora", "Uber",
    "Netflix", "YouTube", "TikTok", "Instagram",
    "Snapchat", "Google", "Apple",
    "Spotify", "Steam",
    "Zalando", "Shein",
  ],
};
