export const CATEGORIES = {
  "Countries": [
    "Sweden","South Africa","Norway","Denmark","Finland","Iceland",
    "Germany","France","Spain","Italy","Portugal",
    "United Kingdom","Ireland","Netherlands","Switzerland",
    "United States","Canada","Mexico","Brazil","Argentina",
    "Japan","China","South Korea","India","Thailand",
    "Australia","New Zealand",
    "Turkey","Greece","Egypt"
  ],

  "Cities": [
    "Stockholm","Milano","Göteborg","Malmö","Uppsala","Åre",
    "London","Paris","Rome","Barcelona","Berlin",
    "Amsterdam","Prague","Vienna","Athens",
    "New York","Los Angeles","Miami","Las Vegas",
    "Tokyo","Seoul","Bangkok","Dubai",
    "Sydney","Rio de Janeiro","Cape Town",
    "Shanghai","Beijing","Kyoto",
    "Bali","Phuket",
    "Istanbul","Ibiza","Madrid",
    "Dublin","Oslo","Copenhagen",
    "Val d'Isere"
  ],

  "Celebrities": [
    "Tom Cruise","Greta Thunberg","Avicii","Zlatan Ibrahimovic","Taylor Swift","Björn Borg","Ingemar Stenmark","Henrik Lundqvist","Sarah Sjöström","Armand Duplantis",
    "Max Martin","Robyn","Håkan Hellström","Veronica Maggio","Carola Häggkvist","Petter","Måns Zelmerlöw",
    "Alicia Vikander","Alexander Skarsgård","Bill Skarsgård","Stellan Skarsgård","Joel Kinnaman",
    "Tove Lo","Lykke Li","PewDiePie","Notch", "Markoolio", "Truls Möregårdh",
    "Stefan Löfven","Jimmie Åkesson","Magdalena Andersson","Ulf Kristersson", "Fredrik Reinfeldt",
    "Benjamin Ingrosso","Loreen","Cornelia Jakobs","David Batra","Petra Mede", "JLC",
    "Zara Larsson","HOV1","Bolaget","Messiah Hallberg","Filip Hammar","Tony Irving",
    "David Hellenius","Pernilla Wahlgren","Henrik Dorsin","Felix Herngren","Tusse",
    "Jonas Andersson (RMM)","Kulan RMM","Johan Rheborg","Robert Gustafsson",
    "Ebba Busch", "Yung Lean","Samir Badran", "Viktor Frisk","Paow","Peter Stormare",
    "Arga snickaren","John Lundvik","Eric Saade","Lotta Schelin","Anis Don Demina", "Dermot Clemenger", "Alexander Ernstberger", "Gunilla Persson",
    "Fröken Snusk", "Pontus Rasmusson", "Edvin Törnblom", "Johanna Nordström",
    "Rickard Olsson","Isabella Löwengrip","Paolo Roberto","Maria Montazami","Leif GW Persson","Jan Emanuel",
    "Rihanna","Ariana Grande","Drake",
    "Ed Sheeran","Billie Eilish","The Weeknd","Justin Bieber",
    "Beyoncé","Dua Lipa","Harry Styles","Eminem",
    "Kanye West","Nicki Minaj","Bad Bunny",
    "Elton John","Madonna","Michael Jackson",
    "Frank Ocean","Sam Smith","Lana Del Rey",
    "Bruno Mars","Shakira","Katy Perry","Olivia Rodrigo",
    "Cristiano Ronaldo","Lionel Messi","Erling Haaland",
    "LeBron James","Serena Williams","Neymar",
    "Roger Federer","Max Verstappen","Lewis Hamilton",
    "Leonardo DiCaprio","Brad Pitt","Tom Hanks",
    "Dwayne Johnson","Johnny Depp",
    "Ryan Gosling","Margot Robbie","Zendaya",
    "Robert Downey Jr.","Chris Hemsworth","Chris Evans",
    "Anne Hathaway","Emma Stone","Jennifer Lawrence",
    "Will Smith","Keanu Reeves",
    "MrBeast","KSI","Logan Paul","IShowSpeed","Sidemen",
  ],

  "Movies & TV": [
    "Breaking Bad","Ove Sundberg","Game of Thrones","Friends","The Office",
    "Stranger Things","Harry Potter","Star Wars", "Arrested Development",
    "The Lion King","Titanic","Inception",
    "The Dark Knight","Forrest Gump","Shrek",
    "Avatar","Frozen","Toy Story","The Simpsons",
    "Interstellar","The Matrix","Jurassic Park",
    "Lord of the Rings","The Hobbit","The Hunger Games",
    "Pirates of the Caribbean","Gladiator",
    "Mission Impossible","Fast & Furious",
    "Black Panther","Guardians of the Galaxy",
    "The Avengers","Deadpool",
    "The Walking Dead","Peaky Blinders",
    "Narcos","Money Heist","The Crown",
    "Wednesday","Squid Game",
    "How I Met Your Mother","Brooklyn Nine-Nine",
    "Family Guy","South Park","Rick and Morty",
    "Minions","Cars","Modern Family", "Störst av allt", "Solsidan", 
    "Darth Vader","Yoda","Spider-Man",
    "Batman","Joker","Iron Man",
    "Walter White","Homer Simpson","Fredrik Schiller"
  ],

  "Objects": [
    "Phone","Snus","Laptop","AirPods","Charger","Powerbank",
    "Wallet","Keys","Backpack",
    "BankID","Swish",
    "Coffee Mug","Water Bottle",
    "Sofa","Bed","Mirror","Lamp",
    "TV Remote","PlayStation Controller",
    "Toothbrush","Shampoo","Perfume",
    "Umbrella","Suitcase",
    "Football","Tennis Racket","Dice","Playing Cards",
    "Skis","Snowboard","Bicycle","Scooter",
    "Credit Card","Passport","Driver’s License",
    "Condom","Lipstick","Makeup Bag",
    "Protein Shake","Energy Drink","UNO Cards","Monopoly",
    "Beer Bottle"
  ],

  "Companies": [
    "IKEA","Systembolaget","Spotify","Volvo",
    "ICA","Apoteket","Klarna","Swish",
    "Max Burgers","SAS","PostNord","Northvolt",
    "Pepsi","Coca-Cola","Heineken",
    "Absolut Vodka","Red Bull",
    "Ben & Jerry’s",
    "Apple","Google","Microsoft","Amazon",
    "Netflix","YouTube","TikTok","Instagram",
    "Snapchat","Uber","Airbnb","Tesla",
    "H&M","Zara","Nike","Adidas","Shein","Zalando","New Balance",
    "McDonald's","Burger King","Starbucks"
  ]
};
